### ISSUE TITLE
Support multiple monitors

### ISSUE THREAD

**Issue by dreamcat4** [emersion/mako#100]
It should be possible to specify *which* monitor(s) notifications are displayed upon. Not just only the primary screen.

You might want them to appear on *all of the monitors*. Or *a specific designated monitor*.

**Comment by vilhalmer** [comment]
I always knew this feature request would show up someday. :)

For "specific designated monitor", I assume you mean allowing this to be set within criteria, since you can currently specify it globally.

**Comment by dreamcat4** [comment]
Yeah I have been looking at notification servers today. And the only one which explicitly advertises multiple monitor support is `dunst`.

The other thing I have been considering today is what about: a program which can masquerade and forward notification requests to a different dbus endpoint address? Then if the user can change the dbus address location, it might be possible to launch multiple notification servers.

Since the official notifications api does not support that feature. It's a kind of a hack. In order to get other types of notifications.

Which I have been discussing in more detail elsewhere https://github.com/UbuntuBudgie/budgie-desktop/issues/44

Ultimately you don't have to implement this: but the main reason I request on your project is because your notification server is for: wayland. And that is maybe something that the other software (`dunst`) does not support. Looking to the future.

**Comment by dreamcat4** [comment]
Well the entire idea of masquerading is that you don't change anything whatsoever in the API (at all). The only thing that has to change is the endpoint dbus address, in each notification server, to be unique.

Which is pretty easy.

**Comment by vilhalmer** [comment]
Is the current multiple monitor support sufficient for what you want to do? If so I'll close this issue, feel free to open a separate one for the customizable bus address if you want to keep that discussion going.

**Comment by dreamcat4** [comment]
Thanks man. Yeah that is absolutely fine. No need to worry about these issues for the time being. If I ever come back to this in future will raise more specific / appropriate issues.

In regards to endpoint address. It on;y makes sense in the presence also of other piece of software, an external daemon, to sit on the bus and forward /rewrite messages.  Which doesn't exist yet.

**Comment by genofire** [comment]
this static variante is not nice - i often replugin different monitors (and use kanshi for it) ...

**Comment by vilhalmer** [comment]
@genofire I'd recommend opening a new issue with a more specific FR.
