### ISSUE TITLE
Support auto-height based on height of text

### ISSUE THREAD

**Issue by SirCmpwn** [emersion/mako#11]
Might be tricky to do this and wrap the text

**Comment by emersion** [comment]
So, it should already work? (Try setting `--height=500` and send a notification)

But the issue is likely that the default format string is `<summary>\n<body>` (and the notification doesn't have a body), so the text ends up having a final `\n`. I guess I should trim spaces.

**Comment by SirCmpwn** [comment]
Yeah, that could be it.
