### ISSUE TITLE
Building makoctl

### ISSUE THREAD

**Issue by bemeurer** [emersion/mako#110]
I'm building mako in my homedir and, following the README instructions, it seems like makoctl is not being built. Am I missing something? Where does that binary go so I can symlink it?

**Comment by emersion** [comment]
It's just a POSIX shell script, it doesn't need to be built.

**Comment by bemeurer** [comment]
@emersion Aha! Just for testing, how do I send the example text from the screenshot with makoctl?

**Comment by vilhalmer** [comment]
You can't send notifications with makoctl, it can only do the things listed in `makoctl --help`. Notifications are received via the D-Bus notification protocol. For manual operation or scripting, `notify-send` is the usual tool.

**Comment by bemeurer** [comment]
@vilhalmer Got it! Thanks! Tested and working :)
