### ISSUE TITLE
Replacing a notification shouldn't create a new ID

### ISSUE THREAD

**Issue by azuwis** [emersion/mako#113]
According to [Desktop Notifications Specification](https://developer.gnome.org/notification-spec/), the `replaces_id` parameter allows replacing active notifications.

> The optional notification ID that this notification replaces. The server must atomically (ie with no flicker or other visual cues) replace the given notification with this one. This allows clients to effectively modify the notification while it's active. A value of value of 0 means that this notification won't replace any existing notifications.

The following commands work on dunst and notify-osd, but do not work on mako:

```
$ gdbus call --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications --method org.freedesktop.Notifications.Notify app_name 1 '' content1 '' '[]' '{}' 10000
$ gdbus call --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications --method org.freedesktop.Notifications.Notify app_name 1 '' content2 '' '[]' '{}' 10000
```

**Comment by emersion** [comment]
>The following commands work on dunst and notify-osd, but do not work on mako

This relies on your first notification having ID 1, which isn't always the case. This works for me:

```shell
busctl --user call org.freedesktop.Notifications /org/freedesktop/Notifications org.freedesktop.Notifications Notify 'susssasa{sv}i' '' 0 '' 'Hey' 'Body' 0 0 0
# busctl outputs the ID of the notification
busctl --user call org.freedesktop.Notifications /org/freedesktop/Notifications org.freedesktop.Notifications Notify 'susssasa{sv}i' '' <previous notification ID> '' 'Hey 2' 'Body' 0 0 0

**Comment by azuwis** [comment]
Does mako follow the following statement?

> If replaces_id is not 0, the returned value is the same value as replaces_id.

That will explain why my command does not work if mako does not follow it.

**Comment by emersion** [comment]
Eh, indeed, the new ID is different.
