### ISSUE TITLE
Add option to dismiss notifications with a command

### ISSUE THREAD

**Issue by ddevault** [emersion/mako#12]
Which could then be bound to a key.

**Comment by emersion** [comment]
Yeah, that's a good idea. I wonder what the IPC for this should be. I guess dbus?

**Comment by SirCmpwn** [comment]
Yeah, in for an inch, in for a mile.

**Comment by SirCmpwn** [comment]
How do I dismiss notifications?

**Comment by emersion** [comment]
```shell
busctl --user call org.freedesktop.Notifications /fr/emersion/Mako fr.emersion.Mako CloseAllNotifications
busctl --user call org.freedesktop.Notifications /fr/emersion/Mako fr.emersion.Mako CloseLastNotification
```

I wonder if a wrapper script would be useful. These calls are pretty painful to hand-write.

**Comment by SirCmpwn** [comment]
My god

Wrapper script please, or an alternate invocation of `mako`

**Comment by emersion** [comment]
Added a `makoctl` script. If the script becomes too complicated, I'll likely migrate it to a standalone executable.
