### ISSUE TITLE
Add a makoctl command to list current notifications

### ISSUE THREAD

**Issue by StephenBrown2** [emersion/mako#121]
I wanted to set up some criteria, as I had with dunst, and I would like to see what the criteria of the notifications are so I can match them more easily.

dunst has a `-print` flag that will output useful information about a notification to write proper rules. As far as I can tell, mako has no such option (yet).

Src[1]: https://wiki.archlinux.org/index.php/Dunst#Filtering
Src[2]: https://github.com/dunst-project/dunst/blob/master/dunstrc#L337-L338

**Comment by emersion** [comment]
Maybe we should instead add a `makoctl` command to get a list of current notifications with all metadata. Could be more useful than just writing criteria easily.
