### ISSUE TITLE
Mako notifications create a whole new window

### ISSUE THREAD

**Issue by ReK2Fernandez** [emersion/mako#126]
... instead of a top corner notification... what is wrong?
is running with latest sway 1.0.x  is doing this since I installed it...

**Comment by emersion** [comment]
Eh?

Can you share a screenshot?

Maybe it's not mako, but another client trying to display a notification but having issues talking to mako and falling back to a stupid thing.

**Comment by ReK2Fernandez** [comment]
@emersion actually this is possible since now that you mention happens only with firefox-wayland notifications.. anyways to remedy this?

**Comment by ReK2Fernandez** [comment]
here are more details:
- like if I have protonmail on a firefox(wayland compiled) tab the notification will open a new window like if I opened any other application and take over a spot on the tiling window order.. instead of been on top and top-right that is the default for mako, going to go into the firefox config see if the firefox own notifications are creating this.

**Comment by ReK2Fernandez** [comment]
@emersion yeah I confirmed, sorry to have posted this here. here is more information of the firefox side https://support.mozilla.org/en-US/kb/push-notifications-firefox
seems like their wayland compile is not doing this right.. feel free to delete this or leave it in case someone else with firefox compiled for wayland thinks is mako...

**Comment by vilhalmer** [comment]
Update from the future: @kennylevinsen determined that having libnotify installed is what triggers Firefox to switch from its internal notification UI to D-Bus. This seems like as good a place as any to document it, since it shows up if you search for Firefox-related issues.

**Comment by mastertinner** [comment]
@emersion, should `libnotify` be added as an optional dependency in Arch Linux?

**Comment by emersion** [comment]
No, mako doesn't provide any extra functionality when libnotify is installed.

**Comment by frei0** [comment]
Note: if you just installed mako, you might have to restart firefox. Both libnotify and a notification daemon have to be installed at firefox's startup.

**Comment by phwelo** [comment]
i've fixed this twice on two different computers now & didn't see anyone mention it.  after installing the notification daemon I had to go into `about:config` and turn the `alerts.useSystemBackend` to `false`, then restart FF, go back in and toggle it to true and then (unsure if required) restarted FF one more time and have working notifications with mako

**Comment by hustodemon** [comment]
Got hit by this as well, in my case it was firejail blocking access to Dbus. Adding this line to the profile solves the problem:
```
dbus-user.talk org.freedesktop.Notifications
```
Maybe it helps somebody.
