### ISSUE TITLE
Criteria hierarchy and examples

### ISSUE THREAD

**Issue by leachim** [emersion/mako#152]
I would like to give different notifications styles to criteria, based on where the notifications originates from. Concrete example: I am using multiple slack work spaces, each of them lives in a different browser tab. Now, when I receive a notification in a specific work space I would like to receive a permanent, sticky notification so I don't miss it. But not for all of the work spaces. 

How can I filter messages from a specific work space? In general, is there a good way to find out the fields/criteria available from a notification? 
Would love to see some more example configurations to see how people handle this in practice for common desktop apps.

**Comment by StephenBrown2** [comment]
I've enabled exact string matching with this diff, as I have similar requirements (want notifications from a particular user to stand out):
```diff
diff --git a/criteria.c b/criteria.c
index 907b09e..ae6dc8c 100644
--- a/criteria.c
+++ b/criteria.c
@@ -262,8 +262,12 @@ bool apply_criteria_field(struct mako_criteria *criteria, char *token) {
                        }
                        criteria->spec.group_index = true;
                        return true;
+               } else if (strcmp(key, "summary") == 0) {
+                       criteria->summary = strdup(value);
+                       criteria->spec.summary = true;
+                       return true;
                } else {
-                       // TODO: summary + body, once we support regex and they're useful.
+                       // TODO: body, once we support regex and they're useful.
                        // Anything left must be one of the boolean fields, defined using
                        // standard syntax. Continue on.
                }
```

My config for that looks like:
```
[summary="New message from Important User"]
background-color=#C40023
border-color=#EB000
```

I don't think we can set _urgency_ or disable _timeout_ via criteria yet, but the background change is a good start for me at least.

**Comment by vilhalmer** [comment]
@StephenBrown2 If you post that as a PR I'd be +1 on it, it's really simple. :) Alternately, I don't think adding regex is actually that difficult. We should use whatever library sway is using for their criteria.

Urgency will never be settable, allowing criteria sections to modify fields provided by the D-Bus spec creates an need for effectively unbounded re-application of criteria to converge on a final style. In better news, you can ignore timeouts via `ignore-timeout=true`.

**Comment by CameronNemo** [comment]
Does sway use regex or globbing? The latter just needs [fnmatch()](https://pubs.opengroup.org/onlinepubs/009695399/functions/fnmatch.html).

**Comment by ascent12** [comment]
IIRC sway uses PCRE for its criteria (because that's what i3 uses). You could get away with simply using POSIX Extended Regular Expressions here, though.

**Comment by vilhalmer** [comment]
@leachim I feel like this issue got off into the weeds a bit, sorry about that. Currently mako doesn't provide a way to dump the entire contents of a notification. Most fields are visible in `makoctl list` on master, see 8bd11f2 (feel free to send a PR to add the missing ones!).

To see absolutely everything, you can use also a command like `dbus-monitor --session interface=org.freedesktop.Notifications` and then send a notification that you'd like to see. For example, if I watch while running `notify-send Hello "This is a notification"`:
```
>> dbus-monitor --session interface=org.freedesktop.Notifications
...
method call time=1559401564.580313 sender=:1.902 -> destination=org.freedesktop.Notifications serial=3 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "notify-send"
   uint32 0
   string ""
   string "Hello"
   string "This is a notification"
   array [
   ]
   array [
      dict entry(
         string "urgency"
         variant             byte 1
      )
   ]
   int32 -1
```

Unfortunately the fields aren't named here because D-Bus itself doesn't know their names, they appear in the order [dictated by this table](https://developer.gnome.org/notification-spec/#basic-design).

**Comment by vilhalmer** [comment]
Gentle ping to see if there's anything else needed here.

**Comment by leachim** [comment]
From my side it is working well now. Thanks for your help!
