### ISSUE TITLE
--ignore-timeout doesn't work with Firefox's "Notifier for Gmail" extension

### ISSUE THREAD

**Issue by koponomarenko** [emersion/mako#154]
Looks like `--ignore-timeout=1` doesn't work with Firefox's "Notifier for Gmail" extension.
When I tried `notify-send -t 2000 hello`, it worked.

**Comment by koponomarenko** [comment]
I tried running mako from command line with `--ignore-timeout=1` parameter, as well as from Sway config. I also tried to use Mako`s config file.

**Comment by vilhalmer** [comment]
Last time someone was having issues with Firefox, it was because Firefox was using its own UI for notifications and not talking to mako at all. Can you verify this one way or the other?

**Comment by koponomarenko** [comment]
Looks like Firefox talks to Mako.
I tried to stop Mako, and Firefox were using a totally different way of showing UI notifications.
It is worth mentioning that my current version of Firefox id `Mozilla Firefox 67.0`, and I use it with enabled Wayland support - `GDK_BACKEND=wayland`.

**Comment by vilhalmer** [comment]
Hmmm, can you provide a link to the extension and I'll try to reproduce?

**Comment by koponomarenko** [comment]
Sure, here is a link to the extension: https://addons.mozilla.org/en-US/firefox/user/13462625/

**Comment by vilhalmer** [comment]
This is a link to ABP.

**Comment by koponomarenko** [comment]
Sorry. It is funny how put a link to a wrong extension =).
Here is the needed one: https://addons.mozilla.org/en-US/firefox/addon/gmail-notifier-restartless/

**Comment by vilhalmer** [comment]
Works fine for me on a fresh Firefox install, your issue lies elsewhere:
![screenshot_2019-06-01-112909](https://user-images.githubusercontent.com/201439/58750447-9c913680-8460-11e9-9457-f98354e212ac.png)

**Comment by vilhalmer** [comment]
Hmmm, yeah, I get the same problem. I'll have to dig into this some more.

(Sorry if you got a notification for my deleted comment, I was testing two things at the same time and forgot what I was supposed to be looking for.)

**Comment by vilhalmer** [comment]
Found it. From `dbus-monitor`:
```
method call time=1559404132.953649 sender=:1.1005 -> destination=:1.982 serial=14 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "Firefox"
   uint32 0
   string ""
   string "Notifier for Gmail\u2122"
   string "From: vil@vil.lv
Title: Test email
Summary: asdf Bill"
   array [
      string "default"
      string "Activate"
   ]
   array [
      dict entry(
         string "desktop-entry"
         variant             string "Firefox"
      )
      dict entry(
         string "image-data"
         variant             struct {
               int32 48
               int32 48
               int32 192
               boolean true
               int32 8
               int32 4
               array of bytes [<snip>]
            }
      )
   ]
   int32 -1
method call time=1559404140.958265 sender=:1.1005 -> destination=:1.982 serial=15 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=CloseNotification
   uint32 3
signal time=1559404140.958651 sender=:1.982 -> destination=(null destination) serial=17 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
   uint32 3
   uint32 3
```
The extension explicitly closes its own notifications. So you have two options: open an issue with the developer of the extension, or open an issue here about adding an option to disallow close requests. I would recommend the former though, this is bad behavior on the extension's part.

I suppose it's also possible this is a limitation of Firefox's extension api, but it doesn't happen for websites that send notifications. (I tested with [the MDN example](https://developer.mozilla.org/en-US/docs/Web/API/notification)).

**Comment by koponomarenko** [comment]
Thanks for the info.

**Comment by koponomarenko** [comment]
Out of curiosity, @vilhalmer , did you use Firefox with Wayland support enabled?

**Comment by vilhalmer** [comment]
It was running under Xwayland during this test.

**Comment by ahmadie** [comment]
can you please add option to disallow close requests ? bcz I use firefox notification on micorosoft team website and it closes notification really fast...

**Comment by emersion** [comment]
This is a Firefox bug, please report it upstream.
