### ISSUE TITLE
Add .service file for DBus activation

### ISSUE THREAD

**Issue by meiyopeng** [emersion/mako#155]
Please add a DBus activation file for mako, so that it can be automatically started when needed.

file: PREFIX/share/dbus-1/services/com.github.emersion.mako.service
content:
```
[D-BUS Service]
Name=org.freedesktop.Notifications
Exec=PREFIX/bin/mako
```

See the "Activation" section of https://www.freedesktop.org/wiki/IntroductionToDBus/.

**Comment by emersion** [comment]
TBH I intentionally left this out because I'm not a fan of D-Bus activation. However since that is how D-Bus works anyway, I guess I'd merge a patch that adds it.

**Comment by meiyopeng** [comment]
Can you specify why you dislike D-Bus activation?  After switching from dunst to mako for mako's Wayland compatibility, I expect mako to work out of the box after installation like any other D-Bus apps.  But instead, mako requires users to manually start it.  I think this is an intrusive problem.

**Comment by emersion** [comment]
There are a number of issues with D-Bus activation. One of them is that D-Bus will start dunst on sway, and probably mako on X11. And I don't really know what happens if two programs expose the same interface: D-Bus chooses a random one?

I don't think making users start mako is intrusive. On the contrary, I think auto-starting mako would be intrusive. It would be similar to making a browser set itself as the default one at install time.

Regardless, this is how D-Bus works, and I don't think fighting D-Bus is a good idea when you're using it. If you want this, please send a patch.

**Comment by meiyopeng** [comment]
> One of them is that D-Bus will start dunst on sway, and probably mako on X11. And I don't really know what happens if two programs expose the same interface: D-Bus chooses a random one?

Indeed.  This is a problem.  And my solution is to install only one notification daemon.  I am not sure if D-Bus provides a mechanism for setting preferences.

> I don't think making users start mako is intrusive. On the contrary, I think auto-starting mako would be intrusive. It would be similar to making a browser set itself as the default one at install time.

But if a user has only one installed browser, he/she should not be asked which browser should be chosen for him/her.

> Regardless, this is how D-Bus works, and I don't think fighting D-Bus is a good idea when you're using it. If you want this, please send a patch.

OK.  I will learn how to do that later.

Thank you for you reply.

**Comment by emersion** [comment]
>And my solution is to install only one notification daemon.

This is not an acceptable solution from a maintainer point-of-view. I can't say to users "mako is The Only Notification Deamon, you should install just mako and nothing else".

**Comment by boucman** [comment]
To answer the dbus part of the question:
Two clients can provide the same interface (or objects) the only level conflict is at the name level, i.e the well-known name to connect on the bus.

Basically, a client will request a name from the dbus daemon and it can pass extra parameters to that request.

* by default, the first requester will get the name and the second one, will just not have the name
* it is possible for the second requester to be enqueued for that name. It will receive a signa from the dbus daemon when the original owner releases the name
* it is possible for the second requester to ask for the name with a high priority flag. If the original requester has requested the name with a low priority flag, then the original requester will loose the name and the second requester will get it

but there is no (simple) mechanism for the /user/ to specify that one client should have higher priority on a name. It might be doable with dbus's firewall rules, but it's not documentented, so it would probably be very hackish...

**Comment by emersion** [comment]
Thanks for the explanation.

**Comment by emersion** [comment]
Fixed in https://github.com/emersion/mako/pull/156
