### ISSUE TITLE
A way to suspend notifications temporarily

### ISSUE THREAD

**Issue by RX14** [emersion/mako#157]
Is sending `SIGSTOP` and `SIGCONT` to mako advisable (i.e. would it cause notification-sending applications to misbehave) or is there a need for a "silent" or "do not disturb" mode set via cli?

**Comment by emersion** [comment]
>Is sending SIGSTOP and SIGCONT to mako advisable (i.e. would it cause notification-sending applications to misbehave) 

It would cause notification clients to misbehave (freeze).

>is there a need for a "silent" or "do not disturb" mode set via cli?

I was thinking about using the feature described in this PR:

https://github.com/emersion/mako/issues/138

Would that be okay for you?

**Comment by RX14** [comment]
yep! that sounds exactly what I have in mind

**Comment by emersion** [comment]
Closing as a dup of #138
