### ISSUE TITLE
Add a way to ignore notifications

### ISSUE THREAD

**Issue by emersion** [emersion/mako#164]
Add a way to drop notifications matching some criteria.

I think @AN3223 is interested in this.

**Comment by matt-snider** [comment]
It would also be interesting to _turn off_ or _silence_ notifications completely (e.g. when in a meeting). Something like:

```sh
$ makoctl disable [--until ...]

# later...
$ makoctl enable
```

When combined with history (see #91) this could be really neat, as `enable` could trigger a notification of its own saying something like "Notifications enabled: 42 missed notifications (use history command to view)".

**Comment by emersion** [comment]
For this, see https://github.com/emersion/mako/issues/138

**Comment by Jpfonseca** [comment]
I have a issue with an app which sents a notificication, and when I click the notification, someone will receive a notification, which will then create another notification. Is there any way to ignore the notification, besides, having to kill mako and launch it again?

**Comment by emersion** [comment]
Send a patch implementing this feature ;)

**Comment by mhmdanas** [comment]
I'd like to get this feature to ignore some rather spammy notifications from Plover:

```
on-notify=exec pw-cat --playback /usr/share/sounds/freedesktop/stereo/message.oga

[app-name=Plover body~="Wayland does not support QWindow::requestActivate\(\)"]
invisible=1
on-notify=dismiss
```

This _almost_ works, but with one (at least as far as I can tell) caveat: mako stores the dismissed notifications in history. What I'm imagining to fix this is adding a new value for `on-notify` (and probably for the other `on-*` events) called `delete` (bikeshedding on name welcome) that would delete the notification entirely.

What do you think? I'm up for sending a patch if you think this idea looks good.

**Comment by emersion** [comment]
I think I'd prefer something like `ignore=1` rather than an `on-notify` hook.

**Comment by mhmdanas** [comment]
That's fine with me too, I'll send a PR when I get the chance.
