### ISSUE TITLE
Can't install mako without systemd

### ISSUE THREAD

**Issue by harrisonthorne** [emersion/mako#165]
Hi, I'm running Gentoo with OpenRC. I would like to install mako without systemd. Would it be possible to do this or to make a change that will allow this?

**Comment by foxcpp** [comment]
As README says:
>If you are using elogind, you might need to manually start a dbus user session:
>`dbus-daemon --session --address=unix:path=$XDG_RUNTIME_DIR/bus`

**Comment by harrisonthorne** [comment]
Here's the output of when I try to install from Gentoo's package manager:

```
Calculating dependencies  ...... done!
[ebuild  N     ] app-arch/lz4-1.8.3  USE="-static-libs" ABI_X86="(64) -32 (-x32)" 
[ebuild  N     ] sys-apps/systemd-241-r1  USE="acl gcrypt kmod lz4 pam pcre resolvconf seccomp split-usr ssl sysv-utils -apparmor -audit -build -cryptsetup -curl -elfutils -gnuefi -http -idn -importd -libidn2 -lzma -nat -policykit -qrcode (-selinux) -test -vanilla -xkb" ABI_X86="(64) -32 (-x32)" 
[ebuild  N     ] sys-apps/gentoo-systemd-integration-7 
[ebuild   R    ] sys-apps/dbus-1.12.12-r1  USE="systemd* user-session*" 
[ebuild  N     ] gui-apps/mako-1.3  USE="icons" 
[blocks B      ] sys-apps/sysvinit ("sys-apps/sysvinit" is blocking sys-apps/systemd-241-r1)
[blocks B      ] sys-fs/eudev ("sys-fs/eudev" is blocking sys-apps/systemd-241-r1)
[blocks B      ] sys-fs/eudev ("sys-fs/eudev" is blocking sys-apps/gentoo-systemd-integration-7)
[blocks B      ] sys-apps/gentoo-systemd-integration ("sys-apps/gentoo-systemd-integration" is blocking sys-fs/eudev-3.2.5)
[blocks B      ] sys-apps/systemd ("sys-apps/systemd" is blocking sys-fs/eudev-3.2.5)
```

**Comment by emersion** [comment]
>Here's the output of when I try to install from Gentoo's package manager

Sorry, I can't provide support for each distribution. This bug is a Gentoo issue, you should ask them what's up.

**Comment by harrisonthorne** [comment]
is systemd a compile-time dependency of mako though? in either case let me know if the requirement for systemd is removed, if ever :) i really like wayland and systemd and would love for mako to have support for openrc without the need for systemd

**Comment by Emantor** [comment]
We don't know why systemd is pulled in for your mako emerge, you should really talk to the gentoo package maintainer. Mako works fine with elogind, if however the packaging on gentoo does not allow for this case, this is not the correct place to raise the issue and can't be resolved here either way.

**Comment by harrisonthorne** [comment]
ah okay. I'll go contact the maintainer. at the very least, this issue has
given me some pointers on what to do 😁 thank you!

**Comment by disruptek** [comment]
The `sorrow` portage overlay has both 1.3 and live ebuilds for mako, which work fine for me in Gentoo with OpenRC.
