### ISSUE TITLE
Lollypop Album Art

### ISSUE THREAD

**Issue by lovesegfault** [emersion/mako#180]
Whenever I use the Lollypop music player under X with dunst, my "now playing" notifications include the album art. On Wayland with mako, however, that does not happen. 

I am not sure whether mako or Lollypop is to blame, but I figured I'd open an issue to investigate

**Comment by emersion** [comment]
Yeah this is probably a mako bug. Need to investigate how Lollypop is submitting images.

**Comment by vilhalmer** [comment]
I think we missed adding the appropriate capabilities when full image support went in.

**Comment by lovesegfault** [comment]
I just checked that using Spotify's electron-based app I get notifications with the album art!

**Comment by emersion** [comment]
>I think we missed adding the appropriate capabilities when full image support went in.

Hmm. We advertise `icon-static`, and I don't think there's anything else we should advertise.

**Comment by vilhalmer** [comment]
`icon-static` is probably the "correct" one for us to advertise, but I'm wondering if Lollypop is using `body-images`. If this ends up being the case, we could advertise it even though it will still display as if it were an icon.

**Comment by vilhalmer** [comment]
Eh, scratch that. Dunst doesn't advertise this either.

**Comment by lovesegfault** [comment]
https://gitlab.gnome.org/World/lollypop/issues/1977

**Comment by loupianche** [comment]
I'm using https://lazka.github.io/pgi-docs/Gio-2.0/classes/Notification.html#Gio.Notification.set_icon in Lollypop.

**Comment by xPMo** [comment]
@lovesegfault  Could you run `dbus-monitor path=/org/freedesktop/Notifications`,  then induce the notification? It may provide some insight for emersion.

**Comment by ascent12** [comment]
That dbus-monitor command wasn't working for me, due to something I can't be bothered looking into, but `busctl --user monitor` gives me this:

```
‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=292
  Sender=:1.159  Destination=org.freedesktop.Notifications  Path=/org/freedesktop/Notifications  Interface=org.freedesktop.Notifications  Member=Notify
  UniqueName=:1.159
  MESSAGE "susssasa{sv}i" {
          STRING "";
          UINT32 0;
          STRING "";
          STRING "モノクロ・インザナイト";
          STRING "by Shibayan Records, from Adrastea";
          ARRAY "s" {
                  STRING "app.shortcut::prev";
                  STRING "Previous";
                  STRING "app.shortcut::next";
                  STRING "Next";
          };
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "desktop-entry";
                          VARIANT "s" {
                                  STRING "org.gnome.Lollypop";
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "urgency";
                          VARIANT "y" {
                                  BYTE 1;
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "image-path";
                          VARIANT "s" {
                                  STRING "/home/scott/.cache/lollypop/@ALBUM@Shibayan Records_Adrastea_2014_200_200.jpg";
                          };
                  };
          };
          INT32 -1;
  };
```
compared to me just using notify-send with the supposedly correct icon
```
‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=7
  Sender=:1.195  Destination=:1.0  Path=/org/freedesktop/Notifications  Interface=org.freedesktop.Notifications  Member=Notify
  UniqueName=:1.195
  MESSAGE "susssasa{sv}i" {
          STRING "notify-send";
          UINT32 0;
          STRING "/home/scott/.cache/lollypop/@ALBUM@Shibayan Records_Adrastea_2014_200_200.jpg";
          STRING "TEST";
          STRING "test test test";
          ARRAY "s" {
          };
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "urgency";
                          VARIANT "y" {
                                  BYTE 1;
                          };
                  };
          };
          INT32 -1;
  };
```
It appears that mako is not handling the [image-path hint](https://developer.gnome.org/notification-spec/#icons-and-images).

**Comment by emersion** [comment]
>It appears that mako is not handling the image-path hint.

Indeed. The easiest way to go would be to set `mako_notification.app_icon` in this chain of `if`s: https://github.com/emersion/mako/blob/master/dbus/xdg.c#L174

**Comment by lovesegfault** [comment]
I'd just like to confirm that testing today this issue has been solved. Thanks everyone!
