### ISSUE TITLE
Stops displaying notifications after swayidle resume

### ISSUE THREAD

**Issue by norcalli** [emersion/mako#184]
I have `swayidle` running which is set to lock the screen after a while using `swaylock` (and also turn off my lights and screen using RS232, so nothing that could be involved with `sway`).

After resuming and unlocking my screen, `mako` no longer displays notifications. I'm guessing this is due to `swaylock` breaking something with the wlr-layer.

**Comment by kennylevinsen** [comment]
Debugging this a bit, it seems like that we end up with `state->frame_pending` true, but having never received the callback, we stall forever.

This sounds like a sway/wlroots issue. It might be related to layer shell's output selection for our surface and the fact that swayidle, when it disabled/re-enabled outputs for idle, destroyed and recreated the output globals.

A workaround could be to re-render on output changes.
