### ISSUE TITLE
SVG icons support

### ISSUE THREAD

**Issue by kisik21** [emersion/mako#185]
I have a full-SVG icon theme (Papirus) and no icons show up. :cry: turns out Mako can't read SVG icons. The icons from Firefox's notifications show correctly, meaning that icon support indeed works.

**Comment by emersion** [comment]
We load images with gdk-pixbuf (`gdk_pixbuf_new_from_file`), so it shoul djust work. Do you have the SVG gdk-pixbuf installed? You can check with e.g. `gdk-pixbuf-query-loaders | grep svg`.

**Comment by kisik21** [comment]
Indeed, the SVG loader isn't present. Closing.
