### ISSUE TITLE
Support for emojis

### ISSUE THREAD

**Issue by aparcar** [emersion/mako#196]
Mako does not support showing emojis which results in partly understandable, partly gibberish messages, would be nice if that would be supported.

**Comment by emersion** [comment]
Works for me.

![](https://sr.ht/p_6b.png)

**Comment by aparcar** [comment]
@emersion Oh well, obviously an issue on my side sorry!

Can you give me an advise if I need to install something in addition or compile it differently?

**Comment by emersion** [comment]
You need to install an emoji font. See e.g. https://wiki.archlinux.org/index.php/Fonts#Emoji_and_symbols
