### ISSUE TITLE
Make notifications move with touch

### ISSUE THREAD

**Issue by rianadon** [emersion/mako#198]
Currently there's little feedback when using touch to dismiss notifications.

It would be great if the notification moved horizontally along with the touch as well as decreased in transparency as it gets closer to the edge of the screen (similar to Windows).

I was thinking about making a PR for this, but wanted feedback before writing code.

**Comment by emersion** [comment]
This requires recognizing swipes (with swap direction) and resizing the layer surface. That sounds complicated, I'd rather not increase code complexity for this feature.

**Comment by rianadon** [comment]
What I had in mind wasn't as complicated, or at least didn't sound as complicated when I ran through it in my mind.

The only required changes would be:
1. For every touch motion, track the initial touch position.
2. On any touch move, compute `dx = touch.x - initialtouch.x`. Constrain `dx`'s absolute value to be no more than some fraction of the notification width so you can't simply drag notifications to the left or right however far you'd like.

    Then re-render the notification with an x offset `dx`. There's probably a more efficient way than re-calling the `render()` function, but that's likely the simplest. The magnitude of `dx` can also be used to determine notification opacity.
3. Dismiss the notification when `dx` passes some threshold.

**Comment by emersion** [comment]
Sorry, I don't want to add this feature.
