### ISSUE TITLE
Only automatically dismiss notification after user interaction

### ISSUE THREAD

**Issue by fuzxi** [emersion/mako#201]
I'd like to set a notification timeout so I don't have to manually dismiss each one, but the timeout starts counting down as soon as the notification is received. This means that if I lock the screen, e.g. with `swaylock`, or simply walk away from the computer, the notification may disappear before I see it. Is it possible to add an option to only dismiss notifications if there is a keypress, click, etc. during the timeout to ensure that the user has the opportunity to see the notification? Perhaps with the use of `swayidle`?

**Comment by vilhalmer** [comment]
This seems like it would become doable after #138.

**Comment by vilhalmer** [comment]
This is now possible using modes, there's an example here: https://github.com/emersion/mako/issues/312#issuecomment-874328559
