### ISSUE TITLE
Feature request: moving notifications

### ISSUE THREAD

**Issue by maralorn** [emersion/mako#203]
The human eye/brain is trained to react to movement in the corner of the eye. So I‘d like to suggest that the notifications (can be configured to) move quickly (e.g. from the next border) into their position, when they are created. This makes notifications much more noticeable and looks cool.

Would you consider this a nice feature to have in mako? Do you think it would be possible to implement with a reasonable amount off effort?

**Comment by Emantor** [comment]
Kinda similar to #89

**Comment by emersion** [comment]
Yeah, animations are something I'd prefer not to support. There's a lot of potential to get lost in many options: some will want fade-in, some slide-from-bottom, some a different animation curve, some apply more complex animations on groups…

Please feel free to experiment with animations in a fork or in a new project.

**Comment by Hubro** [comment]
> Yeah, animations are something I'd prefer not to support. There's a lot of potential to get lost in many options: some will want fade-in, some slide-from-bottom, some a different animation curve, some apply more complex animations on groups…
> 
> Please feel free to experiment with animations in a fork or in a new project.

What about supporting a cusotmization plugin architecture that allows for animations? That way any specific animation implementation would be out of scope of this project.

**Comment by emersion** [comment]
Nack, supporting a plugin architecture would add significant complexity to the project.

**Comment by jficz** [comment]
You can achieve this easily by using a compositor which supports animations, such as Hyprland.
