### ISSUE TITLE
How to define hidden format

### ISSUE THREAD

**Issue by leononame** [emersion/mako#212]
I have tried to specify a hidden format for notifications of a specific category, however I feel like the documentation is wrong or I'm stupid. I have tried the following things, all of which give me an error when starting the daemon:

In the config:
```
hidden-format=%h
```
```
[config:28] Failed to parse option 'hidden-format'
Failed to parse config
```

Setting the option via cli:
```
mako --hidden-format '%h' # Same for -hidden-format=%h
```
```
mako: unrecognized option '--hidden-format'
Failed to parse config
```

If I try to specify something via criteria in the config:
```
[hidden category=backlight]                                               
 width=0 
``` 
```
Invalid boolean criteria field 'hidden'
[config:35] Invalid criteria definition
Failed to parse config
```

However, it works if my criteria is only [hidden], with no other option, which I don't want though. (`[hidden=1]` or `[hidden=true]` does not work). I reinstalled mako-git from the AUR just to make sure I'm on the latest version.

**Comment by vilhalmer** [comment]
Hidden is special, you can only have one hidden format and it can't be combined with any other criteria. At the moment mako determines when to start hiding by simply counting notifications as it draws them. If you want to collapse notifications based on criteria, you can use grouping instead:
```
[category=backlight]
group-by=category
```
Which will look something like:
![screenshot_2020-01-04-080010](https://user-images.githubusercontent.com/201439/71765936-48ec3d00-2ec8-11ea-8c56-df45b9cdf014.png)

**Comment by vilhalmer** [comment]
Also the syntax for changing the hidden format is:
```
[hidden]
format=<whatever>
```

**Comment by leononame** [comment]
Sorry for the delay, I was unavailable. This works for mi if I format the grouped format.
```
[grouped]
format=...
```

Thanks for the help!
