### ISSUE TITLE
makoctl menu doesn't work with more than tree prog arguments

### ISSUE THREAD

**Issue by vyachkonovalov** [emersion/mako#221]
Hi. I'm using [bemenu](https://github.com/Cloudef/bemenu/issues) to select notification action. But this
```shell
makoctl menu bemenu --fn 'Noto Sans Mono 16' -np 'mako'
```
doesn't work (prints makoctl usage instead).
Without last argument to `bemenu` `makoctl` works just fine
```shell
makoctl menu bemenu --fn 'Noto Sans Mono 16' -n
```
Also, just to show the case more clear
```shell
makoctl menu echo 1 2 3
```
works ("No actions found" obviously), but
```shell
makoctl menu echo 1 2 3 4
```
doesn't.

**Comment by emersion** [comment]
Ah, good catch! Can you send a patch to remove the `-gt` comparison here? https://github.com/emersion/mako/blob/master/makoctl#L24

**Comment by vyachkonovalov** [comment]
Sure
