### ISSUE TITLE
Notification resizes after appearing with scale != 1

### ISSUE THREAD

**Issue by maximbaz** [emersion/mako#224]
Set `scale=2` to your output.

When notification appears, it gets resized and is redrawn, which happens very quickly, but irritates the eyes because it kind of "blinks". Particularly noticeable if you have a long notification with many lines (so to reproduce easier, put `height` setting to some big value too).

With `scale=1` the notification appears with the correct size from the beginning.

**Comment by vilhalmer** [comment]
This is a protocol-level issue: https://gitlab.freedesktop.org/wayland/wayland/issues/133

**Comment by maximbaz** [comment]
Ah ok, thanks, will follow that ticket.
