### ISSUE TITLE
Mako do not display icons when invoke from a simple script

### ISSUE THREAD

**Issue by nicoe** [emersion/mako#231]
While I can see an icon with the following command line:

```shell
$ notify-send -i /usr/share/icons/gnome/32x32/status/battery-good.png 'Test'
```

The following script do not display the icon:

```python
import gi
import pathlib

gi.require_version('Gio', '2.0')
from gi.repository import Gio

SIZE = 32
ICON_PREFIX = pathlib.Path(f'/usr/share/icons/gnome/{SIZE}x{SIZE}/status/')


def notify(new_status):
    if not new_status:
        return

    if 'low' in new_status:
        priority = Gio.NotificationPriority.URGENT
        message = "Battery LOW"
        icon = ICON_PREFIX / 'battery-caution.png'
    elif 'charging' in new_status:
        priority = Gio.NotificationPriority.NORMAL
        message = "Battery charging"
        icon = ICON_PREFIX / 'battery-low-charging.png'
    elif 'discharging' in new_status:
        priority = Gio.NotificationPriority.NORMAL
        message = "Battery discharging"
        icon = ICON_PREFIX / 'battery-low.png'
    else:
        priority = Gio.NotificationPriority.LOW
        message = "Battery normal"
        icon = ICON_PREFIX / 'battery-good.png'

    application = Gio.Application.new(
        'battery.notification', Gio.ApplicationFlags.FLAGS_NONE)
    application.register()

    notification = Gio.Notification.new(message)
    notification.set_priority(priority)
    notification.set_icon(Gio.FileIcon.new(Gio.File.new_for_path(str(icon))))
    application.send_notification(None, notification)

notify({'test'})
```

**Comment by vilhalmer** [comment]
If you want to use the full path to the image, you need to send it as the image-path hint, like so:
```
notify-send -h string:image-path:/usr/share/icons/Adwaita/48x48/legacy/battery-good.png 'Test'
```

But the usual way would be to have the icon set you want to use in mako's config and just send the name:
```
notify-send -i battery-good 'Test'
```

**Comment by vilhalmer** [comment]
For anyone who stumbles across this in the future, this is documented here: https://developer.gnome.org/notification-spec/#icons-and-images

**Comment by nicoe** [comment]
* Bill Doyle [février 9, 2020 16:55]:
> If you want to use the full path to the image, you need to send it as the image-path hint, like so:

Thank you but in fact it does work with notify-send (I guess it will
somehow guess that it's a path and do the correct call).

It's with the python script that it does not work (but you're probably
pointing in the right direction, I'll investigate it).
-- 
(°> Nicolas Évrard
( ) Liège
 `¯

**Comment by vilhalmer** [comment]
Hm, actually I was wrong, app_icon does accept a path. It's supposed to be a file: uri though, not a bare path. Mako doesn't actually mind if you provide a bare path, but maybe the wrapper you're using is translating something differently. The output of `busctl monitor --user` while sending the notification might shed some light on it.

**Comment by nicoe** [comment]
* Bill Doyle [février 9, 2020 20:55]:
> Hm, actually I was wrong, app_icon does accept a path. It's supposed
> to be a file: uri though, not a bare path. Mako doesn't actually
> mind if you provide a bare path, but maybe the wrapper you're using
> is translating something differently. The output of `busctl monitor
> --user` while sending the notification might shed some light on it.

Here's an excerpt of the command (it's a surprisingly quite long log for
such a simple task) that I think is relevant let me know if you need
more information.

```
‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=5
  Sender=:1.104  Destination=org.freedesktop.Notifications  Path=/org/freedesktop/Notifications  Interface=org.freedesktop.Notifications  Member=Notify
  UniqueName=:1.104
  MESSAGE "susssasa{sv}i" {
          STRING "";
          UINT32 0;
          STRING "";
          STRING "Battery normal";
          STRING "";
          ARRAY "s" {
          };
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "desktop-entry";
                          VARIANT "s" {
                                  STRING "battery.notification";
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "urgency";
                          VARIANT "y" {
                                  BYTE 0;
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "image-path";
                          VARIANT "s" {
                                  STRING "/usr/share/icons/gnome/32x32/status/battery-good.png";
                          };
                  };
          };
          INT32 -1;
  };
```

Note that I tried using `.get_uri()` on the file returned by
`Gio.File.new_for_path` but it returns a str which is obviously not
the expected type of `Gio.FileIcon.new`.

(I'd like also to point that this script works with dunst, I can't
remember if I said it previously).
-- 
(°> Nicolas Évrard
( ) Liège
 `¯

**Comment by vilhalmer** [comment]
Hmm, if it works with dunst something must be broken.

**Comment by WhyNotHugo** [comment]
This doesn't show any icon on my notification: `notify-send -i battery-good 'Test'`

```
➜ cat .config/mako/config
font=Ubuntu 10
layer=overlay
icons=1
icon-path=/usr/share/icons/Arc/mimetypes/48:/usr/share/icons/Arc/emblems/48:/usr/share/icons/Arc/categories/48:/usr/share/icons/Arc/status/48:/usr/share/icons/Arc/devices/48:/usr/share/icons/Arc/apps/48:/usr/share/icons/Arc/places/48:/usr/share/icons/Arc/panel/22
```

I'm not sure how to help debug this though. Not entirely sure if it's the same issue.

**Comment by CorruptCommit** [comment]
I am not seeing your behaviour using [notify2][0].  This test script shows an icon in mako:

```python
from notify2 import init, Notification
init('test-notification-script')
n = Notification('Title', 'Body', '/usr/share/icons/breeze/apps/48/utilities-terminal.svg')
n.show()
```

If icons are finicky between different approaches, should we revisit #211?

[0]: https://pypi.org/project/notify2

**Comment by vilhalmer** [comment]
@WhyNotHugo does it work if you change your path to just `/usr/share/icons/Arc`? It's not designed to be specified that deeply.

**Comment by WhyNotHugo** [comment]
Ah, yes, that works perfectly! I copied the setting value from `dunst`'s config file, I thought it was the same format.

This is a lot cleaner though, a welcome change. Thanks for the help! ^_^

**Comment by vilhalmer** [comment]
@nicoe I'm taking a look at this again finally. I'm able to get an icon to appear using your script in mako 1.4.1, though I don't have that theme installed so I modified the exact path.

It's worth noting that your original `notify-send` command is using the app-icon attribute, where the script uses the `image-path` hint (Gio is making this decision for you). Nevertheless, they behave the same for me.

**Comment by vilhalmer** [comment]
I think the thumbs up means this can be closed out?

**Comment by vilhalmer** [comment]
Closing because I think this was resolved, reopen if not.
