### ISSUE TITLE
Feature request: allow dismissing grouped messages in one click

### ISSUE THREAD

**Issue by grahamc** [emersion/mako#234]
I have some programs which send me many messages, more than I'd like and in a way I can't easily fix.

Sometimes my notifications look something like this (though this is exaggerated):
 
![image](https://user-images.githubusercontent.com/76716/74368481-bf227000-4da1-11ea-9a99-b9d0db8883df.png)

I'd like to be able to say yes, group by `app-name,summary` and also when I click to ack the notification, dismiss all of them.  Right now I either clear it with the CLI, or by clicking the notification until they are all gone.

**Comment by vilhalmer** [comment]
I feel your pain, I have this same problem with wee-slack. (Though it makes for a good performance test, I suppose.)

**Comment by emersion** [comment]
We could probably add `MAKO_BINDING_DISMISS_GROUP` here:

https://github.com/emersion/mako/blob/175b8d8ab752bcc29da39ff89eca0b274af66628/notification.c#L300

**Comment by qguv** [comment]
Was this fixed by #224? If so, this can be closed :slightly_smiling_face:

**Comment by emersion** [comment]
Indeed, fixed by #244!
