### ISSUE TITLE
Help Desk: "Failed to connect to user bus: Permission denied"

### ISSUE THREAD

**Issue by pkulak** [emersion/mako#238]
It would appear that my dbus service is not allowing mako to connect? That's about as far as I can get in my understanding. I read up on dbus, and there's this whole auth system, with config files, but then how can Firefox/Spotify/etc connect and send messages without jumping through hoops and dropping configs all over the system?

Anyway, thanks so much for the project, and any help if anyone has any idea how I can get this working.

**Comment by aortez** [comment]
Just in case someone else finds themselves here wondering what the issue's resolution was - the discussion for this problem is all over here:
https://github.com/emersion/mako/issues/257
