### ISSUE TITLE
dbus-less IPC

### ISSUE THREAD

**Issue by illiliti** [emersion/mako#241]
Is it possible?

**Comment by emersion** [comment]
No, because the `org.freedesktop.Notifications` spec is using D-Bus, unfortunately.

**Comment by illiliti** [comment]
> No, because the `org.freedesktop.Notifications` spec is using D-Bus, unfortunately.

It's too difficult to implement dbus-less IPC ( via fifo for example ) or you are forced to stick to freedesktop spec? Just curious

**Comment by emersion** [comment]
All programs out there are using the `org.freedesktop.Notifications` D-Bus interface. One would need to create a whole new standard and convince apps to add support for it.

**Comment by illiliti** [comment]
Fair enough
