### ISSUE TITLE
Replacing Notification is not working

### ISSUE THREAD

**Issue by jkehler** [emersion/mako#252]
I'm trying to build a volume and brightness control notification. But it seems the option to replace a notification is not working and its just stacking new notifications every time even though a id is being set.

I was using my own Python script but I also tried using https://github.com/vlevit/notify-send.sh. Both options do not work and just cause new notifications to be stacked.  If I use Dunst it works as expected and the notification is being replaced instead of new ones being spawned.

Any ideas on what is happening and why I can't get this to work on mako?

**Update:**

It seems I can actually make it work occasionally by killing mako and relaunching it. But it seems to be very hit or miss and can't seem to find any pattern to it. When relaunching maybe it might work a handful of times and then it just starts spawning new notifications again.

**Comment by jkehler** [comment]
Nevermind I was an idiot. I found out I have to pass the id of the last notification displayed and not just pass any id i wanted. Closing this issue

**Comment by Inc0ns1st3nt** [comment]
Could you please share on how to obtain the id of the previous notification?
And/or how does one set the id of the notification?

**Comment by emersion** [comment]
The D-Bus `Notify` call will return the ID of the notification.

**Comment by niksingh710** [comment]
> `Notify`

can you please explain it a bit ? How can i obtain the id using dbus?

**Comment by Newchair2644** [comment]
> Could you please share on how to obtain the id of the previous notification? And/or how does one set the id of the notification?
> 
> EDIT: After following the link of notify-send.sh, which is a replacement for notify-send, it seems that notify-send.sh is required for this feature. Still, is there no other ways to replace older notifications?

I have the same issue. `notify-send.sh --replace` works with mako but the notify-send from `libnotify` does not. Is this an issue with mako or notify-send?

**Comment by niksingh710** [comment]
@Newchair2644 
To replace a notification use

```bash
notify-send \
      --hint=string:x-dunst-stack-tag:wallpaper \
      --hint=string:synchronous:wallpaper \
      "$@"
```

make sure to keep these two hint lines same for the next notification again and it will replace the previous one. you can use any `tag`

**Comment by emersion** [comment]
The following works for me:

```
> notify-send -p test
174
> notify-send -r 174 test2
```

**Comment by Newchair2644** [comment]
@niksingh710 @emersion
Thank you for the help, @niksingh710 suggestion seems to work for me (though I don't know why or how) so I will use that since its a bit easier to script than getting the last id.
