### ISSUE TITLE
Add faq to the REAME

### ISSUE THREAD

**Issue by roosemberth** [emersion/mako#254]
Hi!

First of all, great project; a must when moving to sway.

I think it would be a good idea to add an FAQ section to the readme containing questions such as [this](https://github.com/emersion/mako/issues/203) or [this](https://github.com/emersion/mako/issues/196).

Have a nice day!

**Comment by emersion** [comment]
>First of all, great project; a must when moving to sway.

Glad you like it!

>I think it would be a good idea to add an FAQ section to the readme containing questions such as this or this.

Feel free to add these to the wiki.
