### ISSUE TITLE
config file syntax (spaces at =)

### ISSUE THREAD

**Issue by cypa** [emersion/mako#277]
Is spaces at ' = ' allowed? In `man 5 mako` sample options definitions do have, like ' max-visible = n'!
```
~λ cat .config/mako/config 
max-visible = 5
~λ mako
[config:1] Failed to parse option 'max-visible '
Failed to parse config
```

**Comment by emersion** [comment]
I thought we did that, but it doesn't seem the case.

https://github.com/emersion/mako/blob/1c9638c1a00df8ef08f2a19af3acbe2eb3c157a1/config.c#L676

https://github.com/emersion/mako/issues/107#issuecomment-454562203

**Comment by cypa** [comment]
btw I use Archlinux and 
```
~λ pacman --query mako
mako 1.4.1-1
```

**Comment by vilhalmer** [comment]
Do we want to support this, or should the manpage just be made less misleading? I'm kind of a fan of it not being ambiguous how much whitespace should be stripped, tbh.

**Comment by TheAvidDev** [comment]
Perhaps I'll chip in. I think the main issue is the man pages being confusing (I myself was quite stumped). They contain the `key = value` syntax where only `key=value` syntax is allowed. 

From other config files I've seen most either use `key value` or `key=value` so I don't think there's any need to allow for the whitespace of `key = value`.

**Comment by emersion** [comment]
> I'm kind of a fan of it not being ambiguous how much whitespace should be stripped, tbh.

Yeah, the issue with stripping whitespace is that some users might want to intentionally add whitespace for a config option.

I'd be in favor of updating the man page, at least for now.
