### ISSUE TITLE
Better support for actions

### ISSUE THREAD

**Issue by shroff** [emersion/mako#283]
#195 does a decent job of allowing interaction with notification actions via a keybinding to `makoctl menu`, but it's still not quite there for me yet.

I want to be able to interact with any notification (not just the latest one), and also use the cursor to select actions because that is a lot more intuitive for people that I share my computer with.

I have a working solution that doesn't require major modifications or any additional dependencies. I'd be happy to send a PR if the approach seems viable.

Here is my approach:
1. Allow adding custom actions to `on-button-*` and `on-touch`
  a. Add a substitution parameter `%i` that is replaced with the notification id.
2. Allow `makoctl menu` to accept an `id` arg
3. Allow `makoctl dismiss` to accept an `id` arg

This allows a mako config like the following:
```
on-button-left=invoke-custom-action
custom-action=sh -c 'makoctl menu -n %i wofi -d -p "Select Action..." && makoctl dismiss %i'
```

The biggest downside is that it allows for arbitrary command execution on notification click...

**Comment by emersion** [comment]
This PR implements some of this: https://github.com/emersion/mako/pull/249

>Allow makoctl menu to accept an id arg  
>Allow makoctl dismiss to accept an id arg

Yes. We already support this for `makoctl invoke`, so it'd be nice to also do it for those two.

**Comment by emersion** [comment]
Since the only remaining part of this is https://github.com/emersion/mako/issues/38, closing.
