### ISSUE TITLE
Add the ability to temporary disable/pause notifications

### ISSUE THREAD

**Issue by asahaf** [emersion/mako#284]
Hi,

I would be great if we have the ability with IPC to temporary disable/pause notifications (don't disturb), for example during meetings. 

Thanks,

**Comment by emersion** [comment]
Duplicate of https://github.com/emersion/mako/issues/138

**Comment by dafeder** [comment]
Could you point us more specifically to how this is currently accomplished in mako?

**Comment by dafeder** [comment]
Update - for people who this hasn't been intuitive for, you need to add a do-not-disturb mode with invisible=true, and enable/disable that mode. So:

```
[mode=do-not-disturb]
invisible=1
```
then
`makoctl mode -a do-not-disturb`
or
`makoctl mode -r do-not-disturb`
