### ISSUE TITLE
Notification manager

### ISSUE THREAD

**Issue by tukusejssirs** [emersion/mako#285]
I like `mako`. I’ve just started using Sway and I like it, but I miss a notification manager (or how to call it), a place for missed notifications.

Currently, all notifications I have not clicked on, stay on display. I am used to how GNOME 3 and Android does it: show the notification for a few seconds and then (if not dismissed) it disappears and is listed in the notification manager.

Is it possible to create such a place for `mako`/`sway`? For me it would be enough if there would be an icon/module on the panel/bar; if a user clicks on this icon, it would open a window with a list of missed notifications and the user could interact with them (dismiss them, open them, just like with a new / non-missed notification).

**Comment by TheAvidDev** [comment]
I think a separate panel and window would be quite complicated and wouldn't fit with the goal of mako. What `dunst` and `mako`,*do* allow is restoring the previous notification with `makoctl restore` (Side note: I've just tested this and it seems buggy?).

**Comment by emersion** [comment]
As @TheAvidDev pointed out, there's `makoctl restore` available to restore expired notifications.

Apart from this, mako has a D-Bus IPC. It currently exposes the list of displayed notifications (see `makoctl list`). We could expand it to add a signal for new notifications. This would allow a third-party program to implement a notification manager.

**Comment by emersion** [comment]
Closing as per the replies.
