### ISSUE TITLE
Uses -p flag to type, but only requires POSIX shell (jq doesn't exist when it does)

### ISSUE THREAD

**Issue by SevereOverfl0w** [emersion/mako#288]
/bin/sh is symlinked to dash on my system.  The command `type -p jq` under /bin/sh fails, because the `-p` command doesn't exist.

`command -v` is fairly available, or maybe just `type jq` will work well enough?

Alternatively, makoctl could require bash instead.

**Comment by emersion** [comment]
Oh, good point. Yeah, `command -v` sounds more appropriate.

**Comment by emersion** [comment]
Fixed in https://github.com/emersion/mako/commit/b992b49e29d484c0835cd887d0802d979db77956
