### ISSUE TITLE
Layer option not updated on `makoctl reload`

### ISSUE THREAD

**Issue by Isti115** [emersion/mako#290]
While other settings are instantly applied after I save the config file and run `makoctl reload`, I was confused as to why my `layer=overlay` line has no effect until I tried to set it to `background` and realized that the change is not detected at all. After I kill and restart the process, it works as expected, but still doesn't react to change without completely cycling it.

[By the way, I saw some remains of this fullscreen debate somewhere, I agree with the person who said that notifications should in my opinion be drawn above everything else (just missed and important one today because I had a fullscreen window) and such "do not disturb" scenarios, such as watching a movie or presenting should be handled by the notification daemon instead. Anyway, thanks for all the great software you make, they have significantly increased the usability and thus the joy of interacting with my computer! :)]

**Comment by Ongy** [comment]
Probably means that the entire re-association to surfaces is not working correctly.

I'll have a look at it sometime this weekend hopefully.

**Comment by Isti115** [comment]
Thanks for looking into this!
Currently I'm not at home (where my computer is), so I cannot provide the
config, but I will make sure to follow this up, hopefully on the weekend.

**Comment by Isti115** [comment]
Hi! Before attaching my config file I tried it again and now it seems to react properly when updating the config.
As I tend to update pretty frequently I cannot tell what changed in my setup during the last two months that fixed this behavior, but since it's correct now, I guess that it is not really important to figure out whether the fix happened in mako, sway or something else.

ps.: Thank you all for your work! Being able to customize notification appearance based on criteria really made it so much easier to distinguish the important ones! :) The only thing still missing is regex matching.

**Comment by emersion** [comment]
Glad you like it!

Regex support has been added in https://github.com/emersion/mako/pull/275. If this isn't enough for you, feel free to submit a pull request.

**Comment by Isti115** [comment]
Whoa, thanks for bringing that to my attention, I have somehow completely missed that! I will have to experiment a bit, but that has the potential to greatly simplify things! :+1:
