### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by maximbaz** [emersion/mako#292]
Hi guys,

Given that the last release was back in January, what do you think about cutting a new one?

There seem to be quite a number of good changes that people who don't build from master branch could benefit from.

I also spotted several bug reports that were filed against 1.4.1, where the solution is already available on master, so hopefully it would help reducing the noise and confusion a bit.

**Comment by TheAvidDev** [comment]
I use the git version so I forget about these things too, but I agree. Another release would probably be appreciated, especially with the new [multi-surface support](https://github.com/emersion/mako/pull/228) that also got added. Not a core developer or anything, but thought I'd chip in.

**Comment by vilhalmer** [comment]
We have a milestone open with the last stuff we're hoping to get into 1.5: https://github.com/emersion/mako/milestone/2

Unfortunately I haven't been able to pick up anything recently and I'm not sure when that will change.

**Comment by emersion** [comment]
Yeah, I'd like to do a release soon, but I'd to at least fix the `makoctl set` issues so that we don't need to make a breaking change later.

Closing this issue, please watch the milestone if you're interested.
