### ISSUE TITLE
contrib/systemd: use ConditionEnvironment

### ISSUE THREAD

**Issue by emersion** [emersion/mako#294]
Better than spawning a shell. Needs systemd ~~v246~~ v247.

**Comment by maximbaz** [comment]
v246 is out on Arch, but strangely `ConditionEnvironment` isn't being recognized for me. I haven't looked closely, just tried to put it in `[Service]` and `[Unit]` sections, but all I got was the errors below. Might mean we need to wait a bit more for this to become available.

```
/usr/lib/systemd/user/mako.service:9: Unknown key name 'ConditionEnvironment' in section 'Service', ignoring.
/usr/lib/systemd/user/mako.service:9: Unknown key name 'ConditionEnvironment' in section 'Unit', ignoring.
```

**Comment by ammgws** [comment]
I believe that bug has been fixed, so it should be good to use now: https://github.com/systemd/systemd/commit/625a164069aff9efb61dcc5916c572f53c2a7ab0

**Comment by markstos** [comment]
@ammgws It's fixed in systemd 247, which has not been released yet.

**Comment by markstos** [comment]
How will systemd systems with  systemd < 247 be handled? 

Will it be up to package managers to make the package depend on systemd >= 247 once this change is made?

**Comment by emersion** [comment]
`contrib/` material is unsupported. That means it can break/change at any time.

**Comment by markstos** [comment]
This was fixed in https://github.com/emersion/mako/pull/319 and can be closed.
