### ISSUE TITLE
Use of "type -p" in makoctl is non-portable

### ISSUE THREAD

**Issue by craigbarnes** [emersion/mako#296]
When I try to use `makoctl menu` I get the error:

```
/usr/bin/makoctl: jq is required to use 'menu'
```

...despite the fact that `jq` is available.

My `/bin/sh` is symlinked to `dash`, which doesn't appear to support `type -p`, since it's [not specified] by POSIX. I guess the portable solution would be to use [`command -v`].

[not specified]: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/type.html
[`command -v`]: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html

**Comment by emersion** [comment]
Hmm, this reminds me of https://github.com/emersion/mako/commit/b992b49e29d484c0835cd887d0802d979db77956

Is that commit not enough?

**Comment by craigbarnes** [comment]
Ah yeah, that appears to fix it. I was using 1.4.1 and that commit seems to have happened just after the release.

Sorry for the noise; I should have searched for the previous issue.
