### ISSUE TITLE
Notifications do not show up on Wayfire

### ISSUE THREAD

**Issue by snakedye** [emersion/mako#302]
The daemon is running and `makoctl list` shows recent notifications when I run `notify-send 'Hello World!' 'This is a custom notification!'`.

It works fine on Sway.

**Comment by emersion** [comment]
Can you provide a `WAYLAND_DEBUG=1` log of your client?

```sh
WAYLAND_DEBUG=1 your-client >client.log 2>&1
# Then reproduce the bug
```

**Comment by snakedye** [comment]
This command launches a blank window and disables my wallpaper. When I close that window I don't see any logs.

**Comment by TheAvidDev** [comment]
The log should be inside of `client.log`.

**Comment by snakedye** [comment]
[client.log](https://github.com/emersion/mako/files/5431083/client.log)
Here it is

**Comment by snakedye** [comment]
@emersion update?

**Comment by emersion** [comment]
This doesn't look like a client log, this looks like a compositor log.

**Comment by snakedye** [comment]
@emersion 
[client.log](https://github.com/emersion/mako/files/5497549/client.log)

Here's a new one. I used this command `WAYLAND_DEBUG=1 wayfire >client.log 2>&1`.

**Comment by TheAvidDev** [comment]
> Here's a new one. I used this command `WAYLAND_DEBUG=1 wayfire >client.log 2>&1.`

This is the *compositor* (Wayfire) log. emersion if looking for a log of the program you are running, that being `mako`. Try running:
`WAYLAND_DEBUG=1 mako >client.log 2>&1`

*I may be misunderstanding this, and `your-client` refers to something else.*

**Comment by snakedye** [comment]
[mako2.log](https://github.com/emersion/mako/files/5498184/mako2.log)

**Comment by snakedye** [comment]
@emersion ?

**Comment by emersion** [comment]
Sorry, I don't have time to investigate myself.

**Comment by ammen99** [comment]
Wayfire had a bug with mako which was fixed here: https://github.com/WayfireWM/wayfire/pull/843

Can you try with latest Wayfire and see if the bug is still there?

**Comment by snakedye** [comment]
The bug no longer exists in Wayfire.
