### ISSUE TITLE
No documentation on how progress works and possible poor naming

### ISSUE THREAD

**Issue by rileysu** [emersion/mako#303]
I couldn't find any information apart from the source code on how mako handles progress.

Progress is drawn from a hint called "value" which I couldn't find any specification about online in the desktop notification spec.
https://github.com/emersion/mako/blob/a5b6ee9a25b54662906d4846bb4a90631c9d2a08/dbus/xdg.c#L201-L207

If this isn't a standard should this hint be called "value" and should there be some documentation about how it all works with mako? I am happy to contribute both changes.

**Comment by vilhalmer** [comment]
Mako uses the same hint as dunst to support progress: https://github.com/dunst-project/dunst/blob/8831260/src/dbus.c#L427

That doesn't really qualify as a standard though, so it probably makes sense to add to the manpage.

**Comment by rileysu** [comment]
I kinda came across this because I couldn't figure out how to get progress working and had to resort to searching through the code. So if something in the man pages explains it, it would be awesome. Which man page do you think this should go in?

**Comment by TheAvidDev** [comment]
According to `man man`, it should probably go in section 7 (Miscellaneous).

**Comment by vilhalmer** [comment]
I'd also be fine with just mentioning it in section 5 along with the progress config, people don't tend to notice additonal manpages.
