### ISSUE TITLE
Notification criteria for message body?

### ISSUE THREAD

**Issue by daboross** [emersion/mako#304]
Hi!

I'm loving mako so far, and just now looking into its criteria options. It looks like it has a bunch of filters, but weirdly no filter for message body text.

Is this a technical limitation, or could this be added?

My use case is to filter useless notifications from a particular application, [Solaar](https://github.com/pwr-Solaar/Solaar/). None of the other fields really offer any distinction - for the same device, it will use the same summary, app-name, app-icon, category and desktop-entry. The only distinction between different notifications is the notification body text. They've [decided that filtering useless from useful notifications is the job of the notification manager](https://github.com/pwr-Solaar/Solaar/issues/335#issuecomment-612442973), so ideally I'd do this in mako's config.

**Comment by emersion** [comment]
I don't see a reason why not, patches welcome!

(You could also ask Solaar to add an app-specific hint to the notification, if you want a more robust solution.)

**Comment by daboross** [comment]
Sounds good. And thank you for the prompt response! I've just finished and filed #305 for adding this.

Interestingly enough, some of the scaffolding was present in the config code! In any case, lmk if there's anything else I can do.
