### ISSUE TITLE
mako segfaults during program load when installed to /usr/bin

### ISSUE THREAD

**Issue by frei0** [emersion/mako#307]
When mako is installed to any other directory, it works fine. But when run from `/usr/bin` on my system, it segfaults during program load. I have no idea why this might happen or how to debug it further. This is true of both my debian system's packaged mako-notifier 1.4.1-1 and mako that I compiled from github source. 

[Screenshot of my fruitless debugging.](https://i.imgur.com/WoICSI9.png)

My LD_LIBRARY_PATH is empty. Mounts, permissions and ACLs on the directories are identical. All other programs in /usr/bin work fine. I have no idea how this could possibly happen.

**Comment by frei0** [comment]
I should note I haven't been able to reproduce this on my other debian sid system.

**Comment by emersion** [comment]
Hmm. Might have to do with something like selinux or apparmor maybe? Does `dmesg` say anything useful?

**Comment by frei0** [comment]
It is due to apparmor. Switching the profile from enforcing to complain with `sudo aa-complain fr.emersion.Mako` allows mako to run. In complain mode, the following is in my `/var/log/audit/audit.log`:

```
type=AVC msg=audit(1603914590.978:33200): apparmor="ALLOWED" operation="file_mmap" profile="fr.emersion.Mako" name="/usr/bin/mako" pid=1820323 comm="mako" requested_mask="r" denied_mask="r" fsuid=555257 ouid=0
type=SYSCALL msg=audit(1603914590.978:33200): arch=c000003e syscall=59 success=yes exit=0 a0=7f65b3694548 a1=7f65b3694598 a2=565071eb35f0 a3=8 items=2 ppid=1811530 pid=1820323 auid=555257 uid=555257 gid=89939 euid=555257 suid=555257 fsuid=555257 egid=89939 sgid=89939 fsgid=89939 tty=pts1 ses=2968 comm="mako" exe="/usr/bin/mako" subj==fr.emersion.Mako (complain) key=(null)
type=EXECVE msg=audit(1603914590.978:33200): argc=1 a0="/usr/bin/mako"
type=CWD msg=audit(1603914590.978:33200): cwd="/home/frei"
type=PATH msg=audit(1603914590.978:33200): item=0 name="/usr/bin/mako" inode=1337639 dev=fe:01 mode=0100755 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1603914590.978:33200): item=1 name="/lib64/ld-linux-x86-64.so.2" inode=3016171 dev=fe:01 mode=0100755 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PROCTITLE msg=audit(1603914590.978:33200): proctitle="/usr/bin/mako"
```

**Comment by emersion** [comment]
I don't think we can do anything about this. I suggest you report this issue to Debian.

**Comment by m01** [comment]
@frei0 did you report this to Debian?
I think I'm seeing the same issue. As far as I can tell at least in my case `/etc/apparmor.d/fr.emersion.Mako` matches the file in the this repo under [contrib/apparmor/fr.emersion.Mako](https://github.com/emersion/mako/blob/071ed01a7d031dec3f48e43788f7e975cddf6ea0/contrib/apparmor/fr.emersion.Mako).

Unfortunately I don't really understand apparmor enough to know how to debug this properly, but here's my attempt anyway:

Based on the `operation=file_mmap` it seems related to the shared memory created in https://github.com/emersion/mako/blob/071ed01a7d031dec3f48e43788f7e975cddf6ea0/pool-buffer.c#L23, but from my reading of the apparmor profile that should be allowed.
However, `syscall=59` suggests it's `execve` that fails.
I have also read that there may be some rate limiting of the apparmor logs going on, so perhaps this is all a red herring.
hmm.. 😕

**Comment by frei0** [comment]
> As far as I can tell at least in my case /etc/apparmor.d/fr.emersion.Mako
matches the file in this repo.

I did not report this to debian for this reason. It doesn't seem like a
packaging issue to me, though probably debian maintainers should take a
look and decide. I was hoping someone smarter would figure it out.

For now my workaround is to change the policy with "sudo aa-complain
fr.emersion.Mako"

**Comment by m01** [comment]
I tried reproducing this on Arch Linux and seem to have failed so far. I installed `apparmor` as per the [Arch Linux wiki page on Apparmor](https://wiki.archlinux.org/index.php/AppArmor).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
```
# aa-status
...
apparmor module is loaded.
54 profiles are loaded.
54 profiles are in enforce mode.
...
   fr.emersion.Mako
...
4 processes are in enforce mode.
...
   /usr/bin/mako (3335) fr.emersion.Mako
...
```

I also tried to reproduce this in upstream Debian testing in a fresh VirtualBox VM, and the issue doesn't show up there, either. I see a similar output for `aa-status`, showing `/usr/bin/mako` in enforcement mode, using the `fr.emersion.Mako` profile.

I think this may be a setup-specific issue, or something very subtle...
