### ISSUE TITLE
Would you consider switching your dbus interface?

### ISSUE THREAD

**Issue by Phate6660** [emersion/mako#310]
I am asking as somebody who does not use elogind nor systemd. 
It would be nice if this notification daemon wasn't dependent on an init system, or at least, part of it.
I've been wanting to try Mako during Wayland sessions, however this dependency is what's really keeping me away.
For now, I'm still going to be using dunst in XWayland as it can use dbus without needing anything from systemd.
It's far from perfect, there are many issues I've noticed through using a notification daemon via XWayland.
However it's still preferable to... installing systemd whether in whole or in part.

**Comment by emersion** [comment]
I agree the systemd/elogind dependency is annoying. Unfortunately sd-bus is the only not-completely-shitty D-Bus library out there. The plan is to work on [basu](https://github.com/emersion/basu) to fix this.
