### ISSUE TITLE
Pause notification timeout when user has been inactive for a given period of time

### ISSUE THREAD

**Issue by sumnerevans** [emersion/mako#312]
Similar to #263 

This is a feature request to add a configuration option to pause the default notification timeout when the user has been inactive (no mouse or keyboard actions) for a given period of time.

As a user, if I leave the computer, when I return, I want the notifications received since I left to be visible. As soon as I start performing actions (mouse/keyboard), the default notification timeout should commence.

(This functionality is similar to what exists in dunst)

**Comment by vilhalmer** [comment]
I think this would be better handled by using something like `swayidle` to reconfigure mako, but requires #138.

**Comment by sumnerevans** [comment]
Is there an ETA as to when #138 will be implemented?

**Comment by emersion** [comment]
No, we don't do ETAs.

**Comment by nagisa** [comment]
There is an `ignore_timeout` option, which I suspect would achieve this if set by `makoctl set`?

**Comment by emersion** [comment]
Somewhat related to https://github.com/emersion/mako/issues/201

**Comment by emersion** [comment]
This is now possible with something like:

```
swayidle timeout 30 "makoctl set-mode away" resume "makoctl set-mode default"
```

and a mako config which looks like:

```ini
[mode=away]
default-timeout=0
ignore-timeout=1
```
