### ISSUE TITLE
Control notifications with dbus-send?

### ISSUE THREAD

**Issue by edkv** [emersion/mako#318]
I don't have `busctl` on my system, so `makoctl` doesn't work. I have [dbus-send](https://dbus.freedesktop.org/doc/dbus-send.1.html) though which as I understand can be used instead.

Right now I'm interested in finding a way to dismiss all notifications. How do I do it using dbus-send? I looked at how makoctl calls busctl in its source code and tried to do a similar thing with dbus-send, but I don't have experience with dbus, so I can't figure it out. As an example I tried the following which does nothing:
```
dbus-send --dest=org.freedesktop.Notifications /fr/emersion/Mako fr.emersion.Mako.DismissAllNotifications
```

Also, would it make sense for makoctl to use dbus-send instead of busctl, or use one of them depending on what is available in the system?

**Comment by emersion** [comment]
No, we depend on sd-bus for the dbus library, so it makes sense to rely on busctl. I don't how it's possible to get sd-bus without busctl.

**Comment by edkv** [comment]
Ok.

It works with `--print-reply`:

```
dbus-send --print-reply --dest=org.freedesktop.Notifications /fr/emersion/Mako fr.emersion.Mako.DismissAllNotifications
```

**Comment by whoizit** [comment]
same for me, basu not in Void

**Comment by emersion** [comment]
Be the change you want to see.
