### ISSUE TITLE
Failed to connect to user bus: Connection refused (not running apparmor)

### ISSUE THREAD

**Issue by angelus2014** [emersion/mako#322]
Hello,

I've installed Mako on my Calculate (Gentoo) Sway system, but when I try to start it, I get the error: Failed to connect to user bus: Connection refused. I'm not running apparmor (it's not even installed). Dbus was installed with the 'user-session' USE-flag and elogind is running. 'dbus-daemon --session --address=unix:path=$XDG_RUNTIME_DIR/bus' doesn't fix the issue either.

---
Regards,

Angelo

**Comment by emersion** [comment]
Please ask for help to your distribution's support channel.
