### ISSUE TITLE
Freebsd port

### ISSUE THREAD

**Issue by timsofteng** [emersion/mako#323]
Hello. Could you please provide port for freebsd?

**Comment by emersion** [comment]
Build with basu, send patches if anything's not working. Thanks.

**Comment by emersion** [comment]
Eh. basu still doesn't build on freebsd actually. See https://github.com/emersion/basu/issues/6

**Comment by jbeich** [comment]
mako is [now in ports](https://www.freshports.org/x11/mako). Help testing.
