### ISSUE TITLE
Slide into screen 

### ISSUE THREAD

**Issue by WhyNotHugo** [emersion/mako#327]
I use mako with notifications in my upper right corner. I wonder if it's possible for notifications to somehow "slide" down into the screen when appearing.

Is this something that might somehow be doable with existing wayland interfaces? (E.g. reposition like this?).

**Comment by emersion** [comment]
It's possible, but I don't want to add support for animations to mako. Feel free to fork it ofc.

**Comment by WhyNotHugo** [comment]
Might it be possible to do it externally?

I don't want to create a fork, since that duplicating the work done here -- I'd rather try to extend on what's already built.

**Comment by emersion** [comment]
Externally as in not in Sway and not in mako? No, this isn't possible.

**Comment by WhyNotHugo** [comment]
Oh, shame.

Any particular reason for being against this sort of feature? Creating another notification daemon requires duplicating the total amount of work put into maintaining mako, and I honestly think two competing applications in a single space should be a last resort (otherwise we end up with a completely fragmented community).

**Comment by emersion** [comment]
The reason is that the maintenance cost for these eye-candy features is too high.
