### ISSUE TITLE
fullscreen and notify

### ISSUE THREAD

**Issue by n1rdeks** [emersion/mako#328]
In fullscreen mode not show in sway (mpv, firefox).
Message showed, but,  after fullscreen window.
If i change workspace, i see this message.
Sway config with this option: popup_during_fullscreen smart
And Sway+dunst work well.

**Comment by vilhalmer** [comment]
You need to set `layer=overlay` to see mako over full screen windows in sway. See `man 5 mako`.

**Comment by n1rdeks** [comment]
thank you very much. This is New Year...
