### ISSUE TITLE
Bottom padding is shorter than expected (regression)

### ISSUE THREAD

**Issue by muni-corn** [emersion/mako#329]
Hey team, just upgraded to commit 6d743d272e277c74246642f14b5ba2a8fc202919 and am having the following regression.

I have `padding=16,32` in my config. Here's the normal, expected padding from version 1.4.1:

![good padding](https://user-images.githubusercontent.com/33523827/104085178-78840280-520a-11eb-8ad7-6294bbe5ccf3.png)

Here's the problem from the commit above, where the bottom padding seems to be shorter than normal:

![bad padding](https://user-images.githubusercontent.com/33523827/104085197-8c2f6900-520a-11eb-9c09-7f9f9a2b6ad7.png)

**Comment by bc-spreedly** [comment]
I upgraded to 1.5 on Arch today and got this too. My config:

```
# No spaces next to the = sign!
font=Lato 10
padding=4
border-size=8
border-color=#55586566
border-radius=4
text-color=#ffffff
background-color=#555865F4
default-timeout=10000
icons=1
max-icon-size=24
anchor=top-right
sort=+time
progress-color=source #00FF00EF

[urgency=high]
border-color=#FF888844
text-color=#FFFFFF
background-color=#FF8888E8
```

This yields:

![Screenshot at 2021-05-05 11-07-41](https://user-images.githubusercontent.com/78385931/117188805-505c7880-ad92-11eb-8f94-122719a1df98.png)

**Comment by 9ary** [comment]
This was regressed by ffa60aaa60034de3e1927586abccff0992afec93. Messing with that option does indeed affect the placement of the text. The size of the notification remains unchanged, only the positioning of the text is affected.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/167770121-ddea6772-773b-4b47-afb8-28267bc7c9b5.png)

Bump. This is absolutely maddening. I would love to ditch dunst for this, but I cannot get the notifications to align properly.

Adding more padding to the bottom doesn't help at all - it seems to add it to the top as well.

My config:
```
font=Source Code Pro Medium 10
background-color=#272b33
border-size=2
margin=6
padding=5,8
progress-color=#373c47

[urgency=low]
text-color=#98c379
border-color=#98c379
default-timeout=10000

[urgency=normal]
text-color=#61afef
border-color=#61afef
default-timeout=10000

[urgency=critical]
text-color=#e06c75
border-color=#e06c75
default-timeout=0
```
