### ISSUE TITLE
[Feature] overlay only for critical messages

### ISSUE THREAD

**Issue by tigerjack** [emersion/mako#332]
This is lightly related to [this](https://github.com/emersion/mako/issues/328). I can now see messages even if I have an app in fullscreen. However, this can be annoying for low urgency messages. Is it possible to have the overlay option enabled only for critical messages? 
Use case: fullscreen presentation, I don't want to receive notifications for my chat messages, but I need to receive them to warn me that my battery level is low.

**Comment by emersion** [comment]
This feature is already in master. You should just be able to specify a different layer depending on criteria.

**Comment by tigerjack** [comment]
Can you please show an example of this feature? From `man 5 mako` I can't find anything related to layers and criteria.

**Comment by emersion** [comment]
This should do it with mako build from the latest commit:

```
[urgency=high]
layer=overlay
```

**Comment by tigerjack** [comment]
Oh ok so I think I've to compile from source. Do you know when a new official release will be rolled out? Maybe I can wait a little bit more after all :)

**Comment by emersion** [comment]
Here are the blockers for the next release: https://github.com/emersion/mako/milestone/2
