### ISSUE TITLE
Notification history

### ISSUE THREAD

**Issue by aimorris** [emersion/mako#339]
It was stated in #91 that there was a method for viewing notification history via `makoctl restore`, but this command does not exist. How are we to view notification history?

**Comment by fluix-dev** [comment]
This command [was added](https://github.com/emersion/mako/commit/1df9849d7f315994dccfd520c0a29f72676046a9) in February of last year, but that was after the [latest release](https://github.com/emersion/mako/releases/tag/v1.4.1). You should run master or wait for the [next release](https://github.com/emersion/mako/milestone/2),

**Comment by robert-zaremba** [comment]
Could you please tag a release? would be great to have this command in the latest release.

**Comment by fluix-dev** [comment]
Hey, please do a little investigation beforehand by looking at the [releases tab](https://github.com/emersion/mako/releases) or [commit itself](https://github.com/emersion/mako/commit/1df9849d7f315994dccfd520c0a29f72676046a9) (GitHub shows the branch and tags under the commit description). This is included in [release 1.5](https://github.com/emersion/mako/releases/tag/v1.5) and later.
