### ISSUE TITLE
Notifications are shown with 30 seconds delay

### ISSUE THREAD

**Issue by meklonets** [emersion/mako#342]
I think this is not a bug, but couldn't find the info about this.
The problem is telegram notifications arrive with 30 sec delay. But dbus-monitor shows them instantly.
What should I do to make the notifications be instant?
Thank you.

**Comment by emersion** [comment]
Maybe this?

https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start

**Comment by kinshakov** [comment]
@emersion 
Thank you for such very fast reply!
Have tried it now. Restarted swaywm, but no any luck. 30 seconds delay as it was. And I thought Telegram is QT-app, not gtk.
Now I noticed another thing: Sent 5 telegram messages with 2 second interval between each of them. They all have been arrived in mako after 30 seconds and with 2 seconds interval too. I wrote this just as info which, maybe lead to some assumption.

**Comment by kinshakov** [comment]
P.S. The native telegram counter in a tray shows number of unread notifications instantly.

**Comment by kinshakov** [comment]
upd: I resolve my problen on half way. There were set 2 telegram accounts in my app. Remove one of them and notifications started to be instant!
Now, I don't now what should I do? 
Should I compose new question here or in sway, or in telegram? I mean the Q "how to make notifications instantly for telegram which has setting for several accounts"?
