### ISSUE TITLE
Mute desktop notifications

### ISSUE THREAD

**Issue by rapgru** [emersion/mako#343]
Is there a solution for muting mako notifications? I'd like to disable them while sharing my screen for example, so that people in the meeting don't read my conversations with others.

If not, this can be considered a feature proposal. I'd be glad to help!

**Comment by emersion** [comment]
Mako doesn't play any sound. If something plays a sound, it's probably the app sending a notification, and mako has no say in that.

**Comment by rapgru** [comment]
Oh, I mean muting the graphical notifications in the sense of making them invisible. It's not about the sounds, I just want to suppress the notifications from showing on screen.
