### ISSUE TITLE
Per-border margin setting

### ISSUE THREAD

**Issue by hiukky** [emersion/mako#356]
From what I've seen, mako applies the default margin settings in all directions. It accepts a 'margin' property with only one value.

Looking at this code snippet https://github.com/emersion/mako/blob/master/config.c#L81-L84 it seems like a simple thing to increase, but my knowledge of C is minimal.

From what I saw tbm doesn't have 'top | bottom | left | right' properties which would help .. but keeping in mind that we already have the margin property, then it would be great if it had support for new properties like 'margin-top, margin-bottom ... 'or even better css syntax' margin = top | right | bottom | left '.

**Comment by vilhalmer** [comment]
Unless I'm misunderstanding the ask here, we already support this. Both margin and padding are a "directional" which acts like CSS syntax. From the manpage:
```
DIRECTIONAL VALUES
       Some options set values that affect all four edges of a notification. These options can be specified in several different ways, depending on how much control over each edge is desired:

       •   A single value will apply to all four edges.
       •   Two values will set vertical and horizontal edges separately.
       •   Three will set top, horizontal, and bottom edges separately.
       •   Four will give each edge a separate value.

       When specifying multiple values, they should be comma-separated. For example, this would set the top margin to 10, left and right to 20, and bottom to five:

           margin = 10,20,5
```

**Comment by hiukky** [comment]
@vilhalmer this really is it! I didn't have the malice of trying to separate the values with a comma, looking at the documentation with 'man mako' I didn't have much information, but looking at the wiki calmly 'man 5 mako' I got a lot of information, even about DIRECTIONAL VALUES. I just tested and got the result I wanted.

**Comment by hiukky** [comment]
@vilhalmer Back to the problem, there was an untested use case! the first notification actually worked as expected .. but testing again with multiples the margin applies to each item of the notification and not to the general container that involves the notification intems! in this case I defined a top of 60, but it would be for the container to open all notifications below the widget.

![screenshot-22-05-2021 18:04:41](https://user-images.githubusercontent.com/26740246/119240860-019c3600-bb29-11eb-8c8f-12d3ece2858c.png)

**Comment by vilhalmer** [comment]
Ah, indeed. This falls under #236 (just for the opposite end).
