### ISSUE TITLE
Playing a sound on notifications

### ISSUE THREAD

**Issue by adrubesh** [emersion/mako#36]
Are notification chimes something we'd like to implement? Maybe they could be configured based on application with #3?

**Comment by SirCmpwn** [comment]
-1

**Comment by SirCmpwn** [comment]
Maybe just run an arbitrary command when a notification comes in?

**Comment by emersion** [comment]
dunst supports scripts. I've been wondering about supporting scripts too.

**Comment by adrubesh** [comment]
Yeah, the script support would support a much wider range of use cases. I like that.
