### ISSUE TITLE
Add a makoctl command to get the current mode

### ISSUE THREAD

**Issue by Mathew-D** [emersion/mako#367]
I know we have the new set-mode but is there a way to display what the current active mode is?

**Comment by emersion** [comment]
There's no way to do this right now.

We could add a makoctl command to get the current mode, however need to be careful about possible future extensions. Maybe at some point we'll allow multiple modes to be active at the same time.

**Comment by Diegovsky** [comment]
Hey, would it be possible to instead return an array of current modes? that way future extensibility wouldn't be a problem, I think

**Comment by emersion** [comment]
`makoctl mode` prints current modes.

**Comment by Diegovsky** [comment]
Cool, thanks :)
