### ISSUE TITLE
makoctl should communicate with mako using unix sockets, not DBUS

### ISSUE THREAD

**Issue by mitinarseny** [emersion/mako#371]
Not everyone has DBUS and more and more people (like me) would like to stop using it at all. Unfortunatelly, some really good software (like mako) out there is still using DBUS and this is the only reason why I still have DBUS running in my system.  
Linux has a traditional UNIX way to allow processes to communicate with each other - UNIX sockets. Why using DBUS when there is a much cleaner and STABLE solution like UNIX sockets?

Having that said, is it possible to build mako without DBUS support?

**Comment by vilhalmer** [comment]
Mako is a D-Bus notification daemon, it has no other way of receiving notifications to display. `makoctl` cannot inject notifications. There's a D-Bus-free notification tool called [herbe](https://github.com/dudik/herbe) for X, but I am not aware of an equivalent project for Wayland. A separate project for this would make more sense than trying to support some extra custom protocol in mako.

**Comment by emersion** [comment]
To expand on this a bit: applications which open notifications all use the standard FreeDesktop.Org D-Bus API. One would need to patch all of these apps to be able to build a system without D-Bus.
