### ISSUE TITLE
Mouse cursor theme ignored

### ISSUE THREAD

**Issue by philidor-green** [emersion/mako#372]
Current setup

 - arch linux
 - mako 1.6-1
 - cairo 1.17.4-5
 - sway 1:1.6.1-1
 - wlroots 0.14.1-1

https://user-images.githubusercontent.com/3471384/128675155-12d45ea2-a167-4f51-80bb-bfba2eca4a03.mp4

**Comment by emersion** [comment]
We need to read the `XCURSOR_THEME` variable here instead of NULL:

https://github.com/emersion/mako/blob/6151ecb3ef241782366b4b7708e0e509a9d07a95/wayland.c#L468

Would you be willing to work on a patch?

**Comment by philidor-green** [comment]
@emersion I'll try, do you have any contribution guide? `c` isnt my primary languare.

**Comment by emersion** [comment]
Feel free to ping me in #emersion on Libera Chat.

**Comment by GreyXor** [comment]
Hello, I have to reopen this issue as my cursos theme is ignored
[recording.webm](https://github.com/emersion/mako/assets/79602273/331a2e93-b37c-45e5-b0c1-ce1f01e3e802)

**Comment by fluix-dev** [comment]
And is mako running with said environment variable?

**Comment by GreyXor** [comment]
> And is mako running with said environment variable?

I don't know, surely not. I have disabled the user systemd service `mako` and added `exec mako` in my sway config

**Comment by bluebyt** [comment]
I have the env variable set to my theme.
$echo $XCURSOR_THEME 
Bibata-Modern-Classic

If I start mako as a service, I have the same problem. 
$systemctl --user start mako

But I just start mako in my hyprland.conf that solved the problem.
exec-once = mako

Maybe there is a way to set the env variable for service.

**Comment by GreyXor** [comment]
> I have the env variable set to my theme. $echo $XCURSOR_THEME Bibata-Modern-Classic
> 
> If I start mako as a service, I have the same problem. $systemctl --user start mako
> 
> But I just start mako in my hyprland.conf that solved the problem. exec-once = mako
> 
> Maybe there is a way to set the env variable for service.

My cursor theme is changing, based on my `org.gnome.desktop.interface` prefer-dark. (I have white cursor theme when I `prefer-dark` and I have dark cursor theme when I `prefer-light`
