### ISSUE TITLE
makoctl dismiss -n

### ISSUE THREAD

**Issue by Berjou** [emersion/mako#374]
From `makectl --help`, there is the description of the `dismiss -n` option:

```
dismiss [-n id]                  Dismiss the notification with the
                                 given id, or the last notification
                                 if none is given
```
However, when invoking `makoctl dismiss -n` without an id, mako gives me the following error:

`usr/bin/makoctl: Expected <id> after '-n'`

**Comment by emersion** [comment]
Use `makoctl dismiss` instead.

**Comment by Berjou** [comment]
Yeah, obviously... I should get some sleep. Sorry for that.
