### ISSUE TITLE
Possible to use more than one font?

### ISSUE THREAD

**Issue by rieje** [emersion/mako#384]
Is it possible to use more than one font? E.g. specify font families so that something like `font=JetBrainsMono SemiBold 12, FontAwesome 12` will use JetBrains for text and FontAwesome for icons? I have this set and FontAwesome is used for both text and icons (text with FontAwesome looks pretty bad).

**Comment by emersion** [comment]
See https://docs.gtk.org/Pango/type_func.FontDescription.from_string.html

Maybe try `font=JetBrainsMono SemiBold, FontAwesome 12`?

**Comment by rieje** [comment]
Works, thank you.
