### ISSUE TITLE
"action" interaction is undocumented

### ISSUE THREAD

**Issue by nmschulte** [emersion/mako#389]
How does this work?  Left click performs the (default) action, any other click dismisses?  What happens in the case of multiple available actions, like BlueZ/blueman (yes, yes+always, no, ...)?

Dunst is neat, it's `context` shortcut lets you discover/see the interactions (around the "action(s)"), and does this automatically if there is no "default action."

**Comment by emersion** [comment]
There's `makoctl menu` to trigger actions.
