### ISSUE TITLE
Support choosing a notification action

### ISSUE THREAD

**Issue by emersion** [emersion/mako#4]
Do we want to use dmenu for this?

**Comment by zetorian** [comment]
perhaps it would be better to add a configuration option for a choosing command to run. ie "--<whatever_want_to_call_it>=dmenu | rofi | whatever else" so that it is possible to support wayland native dmenu alternatives as they appear without a major rewrite.

**Comment by emersion** [comment]
Sure

**Comment by xPMo** [comment]
Alternative: `makoctl get_actions` or similar and then the user can script around its output.

**Comment by emersion** [comment]
That would be nice too. Maybe we want both to be able to click on a notification to open the menu?

**Comment by dg10a** [comment]
In case it's useful to anyone, here's a script to handle notification actions with the currently available options. You can swap out `rofi` for your preferred menu.

```sh
#! /bin/sh

while true
do
    notifications=$(makoctl list)
    actions=$(echo $notifications | jq '.data[0][0].actions.data')
    if [ $(echo $actions | jq 'type') == "\"object\"" ] && [ $(echo $actions | jq 'length') != "0" ]; then
        selection=$(echo $actions | jq 'values[]' | sed 's/" "/"\n"/g' | sed 's,.\(.*\).$,\1,g' | rofi -p "Select notification action" -dmenu)
        if [ -n "$selection" ]; then
            selection_key=$(echo $actions | jq -r --arg sel "$selection" 'to_entries[] | select(.value == $sel) | .key')
            makoctl invoke $selection_key
        fi
        makoctl dismiss
    fi
    sleep 0.5
done
```

**Comment by xPMo** [comment]
Why is it wrapped in a `while true ... sleep`?

Also, here's an alternate script, moving logic into `jq` and using `jq --exit-status`:

```sh
if actions_object="$(makoctl list | jq -re '.data[0][0].actions.data | if length > 0 then . else false end')"; then
	makoctl invoke "$(jq -rn --arg sel "$(
			jq -rn "$actions_object|values[]" |
			rofi -dmenu -p "Select action: "
		)" \
		"$actions_object|to_entries[]|select(.value == \$sel).key"
	)"
fi
```

**Comment by dg10a** [comment]
Thanks @xPMo, your script is much cleaner. I was using the script as a background process to intercept actionable notifications, hence the `while true ... sleep`.

Maybe `--select-action` of `--dmenu`?

**Comment by xPMo** [comment]
I found out during the course of writing the POSIX+no-jq variant that actions and keys can have newlines or other difficult characters. `busctl` will print them as C-style escapes, so what I did is leave them escaped (that means you see `action with\nescaped newlines` in dmenu/rofi/etc.), and then fix them at the end:

```sh
if [ -n "$selection" ]; then
    # The key may contain C escape sequences, use printf %b to evaluate them.
    # Due to how command substitutions occur, trailing newlines are mangled.
    # Append another character to prevent this.
    selection="$(printf '%b:' "$selection")"
    makoctl invoke "${selection%?}"
fi
```

**Comment by xPMo** [comment]
I do encourage anyone to review [my POSIX sh script](https://gist.github.com/xPMo/462936ca0e86f3697a6365b2be02525d), I would like to contribute it in some form to mako, but it would be wise to make sure all the following hold:

- The best way to handle multiple lists in sh is to `set --` them together, keeping track of the length/offset of each.
- It correctly evaluates all C escape sequences.
- The obtuse sh boilerplate is commented clearly enough for future maintenance.
- @emersion thinks it would make a good fit in either makoctl or contrib/bin/makomenu

**Comment by dg10a** [comment]
Your example isn't working for me. When I use `dunstify --action "key\n\n,val\n\n" "Test"` with your escape functionality the action isn't received.

The same thing happens with your POSIX sh script. I think `busctl` is actually expecting the escaped string.

**Comment by xPMo** [comment]
> your example works but it breaks this case.

Care to explain exactly what `--action` breaks as a comment over there?

**Comment by dg10a** [comment]
Sorry, my comment wasn't very clear. I was using this [revision](https://gist.github.com/xPMo/462936ca0e86f3697a6365b2be02525d/75e3fa70bf799ca71f4217cfe02cc35ee3827b17), which worked with `dunstify --action=$'key\n\n,val\n\n' "Test"` but not with `dunstify --action "key\n\n,val\n\n" "Test"`.

Both work now with the latest revision.

**Comment by niksingh710** [comment]
> Thanks @xPMo, your script is much cleaner. I was using the script as a background process to intercept actionable notifications, hence the `while true ... sleep`.
> 
> Maybe `--select-action` of `--dmenu`? EDIT: Here's what I'm using now. I added the check because `rofi` can return without a value.
> 
> `bindsym $mod+a exec mako-select-action rofi -dmenu -p "Select action"`
> 
> ```
> #! /bin/sh
> # mako-select-action
> 
> if actions_object="$(makoctl list | jq -re '.data[0][0].actions.data | if length > 0 then . else false end')"; then
> 	selection="$(jq -rn --arg sel "$(
> 			jq -rn "$actions_object|values[]" |
> 			$@
> 		)" \
> 		"$actions_object|to_entries[]|select(.value == \$sel).key"
> 	)"
> 	if [ -n "$selection" ]; then
> 		makoctl invoke $selection
> 	fi
> fi
> ```


This is nice but what i am trying to acheive is 
listing all notifications from history in rofi and showing the title and summary in the rofi msg box at time of scrolling through them and as soon as i select the notification it shows me the available action with it.
i am unable to figure out how to incoke action from the history of notifications

**Comment by emersion** [comment]
Once a notification has been dismissed, I don't think it's possible to invoke an action on it. `NotificationClosed` invalidates the notification ID.

**Comment by niksingh710** [comment]
> Once a notification has been dismissed, I don't think it's possible to invoke an action on it per the spec. `NotificationClosed` invalidates the notification ID.

Aah isn't there any hack around it to keep it available for the x amount of history notification?

**Comment by adonespitogo** [comment]
Hi, I'm new to hyprland and using mako as my notification daemon. I'd like to know if anyone knows how to handle bluetooth pairing confirmation? Mako is showing confirmation code but I have no way to click to confirm the pairing request. Any advise would be appreciated.

**Comment by adonespitogo** [comment]
I was able to confirm bluetooth connection using the example in the PR:

```
makoctl menu wofi -d -p 'Choose Action: '
```

But I had to manually type this in the terminal while the notification is still active. I'd like to know how to automatically invoke this using mako config.

**Comment by adonespitogo** [comment]
Sorry for spamming, but I got it working by adding this line to mako config:

```
# ~/.config/mako/config
on-notify=exec makoctl menu wofi -d -p 'Choose Action: '
```

**Comment by jkimsis** [comment]
> I was able to confirm bluetooth connection using the example in the PR:
> 
> ```
> makoctl menu wofi -d -p 'Choose Action: '
> ```
> 
> But I had to manually type this in the terminal while the notification is still active. I'd like to know how to automatically invoke this using mako config.

Hello,

trying to do this two years later on a Niri machine, it isn't working. I'm getting the following error:
`# makoctl menu "wofi -d"execvp() failed: No such file or directory
No action selected`

**Comment by emersion** [comment]
You need to leave out the quotes.

**Comment by emersion** [comment]
Maybe try `makoctl menu -- wofi -d`?

**Comment by jkimsis** [comment]
Ok, now it works. Adding `on-notify=exec makoctl menu -- wofi -d` to ~/.config/mako/config also brings up the confirmation dialog automatically.

**Comment by LiAlH4qwq** [comment]
sorry for spamming, but according to
 latest manpage, this solution may be perfect.

It matches actionable notifications, launch dmenu for choosing action, then dismiss it. All you need is clicking left button, like for non-actionable ones. And it works when there're more than one notifications.
```ini
[actionable]
on-button-left=exec makoctl menu -n $id -- vicinae dmenu && makoctl dismiss -n $id
```
