### ISSUE TITLE
Respect $XDG_CONFIG_DIRS

### ISSUE THREAD

**Issue by kisik21** [emersion/mako#400]
Relevant specification: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

TL;DR: check `$XDG_CONFIG_DIRS` one by one if `$XDG_CONFIG_HOME` doesn't yield a config.

> `$XDG_CONFIG_DIRS` defines the preference-ordered set of base directories to search for configuration files in addition to the `$XDG_CONFIG_HOME` base directory. The directories in `$XDG_CONFIG_DIRS` should be seperated with a colon ':'.
>
> If `$XDG_CONFIG_DIRS` is either not set or empty, a value equal to `/etc/xdg` should be used.
>
> The order of base directories denotes their importance; the first directory listed is the most important. When the same information is defined in multiple places the information defined relative to the more important base directory takes precedent. The base directory defined by `$XDG_DATA_HOME` is considered more important than any of the base directories defined by `$XDG_DATA_DIRS`. The base directory defined by `$XDG_CONFIG_HOME` is considered more important than any of the base directories defined by `$XDG_CONFIG_DIRS`.

**Comment by emersion** [comment]
I don't really like $XDG_CONFIG_DIRS. It adds a whole bunch of complexity and isn't really useful in practice.

**Comment by kisik21** [comment]
I do have a niche use-case of dropping in system-wide default configs there so I won't have to clobber my home directory (I'm using NixOS so it's really easy to do this, and I don't even need home-manager which I don't like). Currently what I'm doing as a work-around is just configuring mako via command-line arguments (thankfully mako exposes the whole config surface via command-line) when launched via sway config.

So if you don't want to implement it, it's okay.

**Comment by kisik21** [comment]
Feel free to mark this as a "wontfix" if you want to.

**Comment by eddsalkield** [comment]
I'm solving this with the following shell script:
```
#!/bin/sh
if [ ! -f "${XDG_CONFIG_HOME:-$HOME/.config}"/mako/config ] && [ -z "$XDG_CONFIG_DIRS" ] && [ -f "/etc/xdg/mako/config" ]; then
    /usr/bin/mako -c "/etc/xdg/mako/config"
    exit 0
fi

if [ ! -f "${XDG_CONFIG_HOME:-$HOME/.config}"/mako/config ] && [ -n "$XDG_CONFIG_DIRS" ]; then
    IFS=":"
    for path in $XDG_CONFIG_DIRS; do
        if [ -f "$path"/mako/config ]; then
            /usr/bin/mako "$path"/mako/config
            exit 0
        fi
    done
fi

/usr/bin/mako
```
