### ISSUE TITLE
Can't emerge Mako anymore

### ISSUE THREAD

**Issue by FromOopsToOps** [emersion/mako#408]
Mako version on repo: 1.6
Repo: Sorrow
Linux: gentoo, mostly amd64, few ~amd64 here and there

I can't emerge Mako anymore.

emerge: there are no ebuilds built with USE flags to satisfy "sys-apps/dbus[user-session]".
!!! One of the following packages is required to complete your request:
- sys-apps/dbus-1.12.20-r4::gentoo (Missing IUSE: user-session)
(dependency required by "gui-apps/mako-1.6::sorrow" [ebuild])
(dependency required by "gui-apps/mako" [argument])

There's no USE flag for dbus regarding user session.

Calculating dependencies... done!
[ebuild   R    ] sys-apps/dbus-1.12.20-r4::gentoo  USE="X systemd -debug -doc (-elogind) (-selinux) -static-libs -test" ABI_X86="32 (64) (-x32)" 0 KiB

As you can see I've built dbus with systemd. Looking at the ebuild I see:

IUSE="debug doc elogind selinux static-libs systemd test X"
		$(use_enable systemd user-session)

My understanding is that enabling systemd implicitly enables user-session and there's no explicit IUSE for user-session.
Since Mako requires it to be explicit I can't emerge it.

Help?

**Comment by emersion** [comment]
Closing because this isn't an upstream mako bug. Please report a bug for your distro instead.
