### ISSUE TITLE
Dispatching notifications from dbus system instance to session dbus instances

### ISSUE THREAD

**Issue by VannTen** [emersion/mako#412]
I would like to dispatch a notification send from a service running in the system service manager to each currently connected user.
(The service in question is `transmission-daemon`, and the purpose would be to send a notification when a torrent is finished downloading.

At first, I thought I could be able to run a mako as a system service, and use something like `on-notify = exec foreach user; do DBUS_SESSION_BUS_ADDRESS=<user_bus_address> notify-send <notif_content>;done`. But I don't see how to access the notification with makoctl in a format suitable to use it with notify-send, without loss.
And I'm also not sure if mako should be used this way.

Do you know of is there is a "notifications dispatcher" doing this which I could use ?

Thanks

**Comment by emersion** [comment]
Sorry, mako is not designed to be run on the system bus. The FreeDesktop spec says:

> all notifications are controlled by a single session-scoped service

**Comment by vilhalmer** [comment]
I've done something similar using this script, but it needs to be running as root to get access to each bus so you may have to do some contortions to attach it to transmission: https://git.sr.ht/~vilhalmer/coredump-notify/tree/main/item/coredump-notify
