### ISSUE TITLE
[Feature request] makoctl restore N; reste the most recently N expired notification

### ISSUE THREAD

**Issue by kiuKisas** [emersion/mako#417]
Hi, I play with my config these days and I try to build a light notification center with mako. Through a shortcut, I want to be able to see the last N (let's says 10) last notifications, and toggle theses notifcations with `makoctl dismiss -a`. So it force me to call `makoctl restore` N times. For references:
```sh
#!/bin/sh
# mako_center.sh
for i in {1..10}; do makoctl restore; done
```

 Working great though ! But I think it could be nice to add an option to `restore` a given number of the latest notification, so it can be done in one call.

**Comment by emersion** [comment]
This sounds a bit workflow-specific. I'm a bit worried about potential future feature requests, e.g.

- restore the last 10 notifications, except this particular notification
- restore the last 10 notifications with the following app-id/category/etc
- restore the following notification ranges
- etc

I think a more generic API would be to take a list of notification IDs to restore. Would require a bit more work on your side though (need to parse the output of `makoctl list`, pick the last 10 IDs, and pass that to `makoctl restore`…).

**Comment by kiuKisas** [comment]
Got it, I was asking just in case but I also though that it might be out of scope. Indeed, wee can imagine a `makohandler` as a generic API to provide more "out-of-the-box" option without adding complexity. Could also be "daemon agnostic" scripts, with port for similar daemons.. Let's see, I let you know if I ding into this ;).
