### ISSUE TITLE
Unable to launch mako

### ISSUE THREAD

**Issue by josteink** [emersion/mako#425]
When trying to launch mako, I get the following error:

````
$ mako
Failed to acquire service name: File exists
Is a notification daemon already running?
$ 
````

According to the source, this is due to the inability to register a dbus namespace:

https://github.com/emersion/mako/blob/55104d36575230d57af007cd9e7d53cb3a92a96e/dbus/dbus.c#L32-L38

That said, I can't see any other notification deamons running:

````
$ ps -ef | grep -i notification
jostein  1285232 1283282  0 12:17 pts/1    00:00:00 grep --color=auto -i notification
$ 
````

While probably not a fault of mako itself, this error prevents me from running mako in my setup... So any help on how to resolve it would very much be appreciated :smile: 

**Environment info:**

* Ubuntu 21.10 desktop - Intel x64
* sway (1.5.1) from apt
* mako (1.4.1) from apt

**Comment by emersion** [comment]
Can you try

```
busctl --user list | grep org.freedesktop.Notifications
```

**Comment by josteink** [comment]
Thanks for the super-quick response!

Running that shows me running something called "dunst".

````
$ busctl --user list | grep org.freedesktop.Notifications
org.freedesktop.Notifications                   21963 dunst           jostein :1.176        user@1000.service -       -
$ 
````

Not sure what's starting it, but killing it allows me to start mako :partying_face: 

````
$ killall dunst
$ mako
(keeps running)
`````

**Comment by emersion** [comment]
Yeah, you'll need to either start mako explicitly in the Sway config file, or uninstall dunst.

**Comment by josteink** [comment]
Sure thing. Thanks for the help!
