### ISSUE TITLE
mode seems to be broken in v1.7

### ISSUE THREAD

**Issue by fauust** [emersion/mako#437]
Hi!
After upgrading to 1.7, I can't see any notification if a mode is defined in my configuration:
```console
$ cat ~/.config/mako/config
font=Iosevka 12
default-timeout=10000
layer=overlay
border-size=2
background-color=#2e3440
border-color=#4c7899
max-icon-size=32
height=150
width=400

[mode=dnd]
invisible=1
```

When I activate the dnd mode, then I see notifications again (which should not be the case because of `invisible=1`):
```console
$ killall mako
$ notify-send test # no notification
$ makoctl mode -s dnd # test notification appears
$ makoctl mode
dnd
$ notify-send test2 # also appears
```

If I comment the last 2 lines (mode conf) and reload configuration (or restart mako), then notifications in default mode appears again.

Environment:
```console
$ sway --version
sway version 1.7-5543acff (Apr  6 2022, branch 'HEAD')
```

**Comment by emersion** [comment]
Oops, sorry about that!
