### ISSUE TITLE
Show notifications on top or above all other windows.

### ISSUE THREAD

**Issue by migonos0** [emersion/mako#443]
Background: I use mako along sway to show an alert whenever my battery level is under a critical level but if any application is in fullscreen mode the mentioned notification is not visible, so I end up ignoring the alert and for instance my computer shutting down.

Use case: Showing crucial notifications above any window.

Question: Is there any way to tell mako to show itself above any window?, Is this use case more related to sway?

Thanks for reading!

**Comment by emersion** [comment]
Yes, `layer=overlay`. See the man page.
