### ISSUE TITLE
FR: Provide urgency in makoctl list output

### ISSUE THREAD

**Issue by Jadarma** [emersion/mako#446]
I would like to make a script that gives me the count of current notifications, but ignoring low urgency ones.

I can get the total count with something like `makoctl list | jq '.data[] | length'`, however the output does not specify the urgency so I can filter them out.

Would it be possible to also have an entry like this inside the payload for each notification?

```json
"urgency": {
  "type": "s",
  "data": "critical"
}
```

Or, if not, is there any other method I could use to achieve my use case?

**Comment by emersion** [comment]
Sure, patches welcome.

(Maybe we should use the same values as the spec, instead of an ad-hoc string.)
