### ISSUE TITLE
use replace_id as id for new notifications.

### ISSUE THREAD

**Issue by Wielding** [emersion/mako#455]
It would be nice if the replacement id in the notification could be used as the id for new notifications if mako does not have any other notifications with that id.  I have an app that connects to an api and generates notifications but the notification id was created on a different device.  The remote device can send a dismissal event for me to remove the notification with the same id but since mako always generates a new id it is not possible to match it up to the mako notification to invoke a dbus CloseNotification event. When I use dunst or SwayNotificationCenter they use the replacement id for new notifications and work as expected but I much prefer mako.

I had modified mako on my own to handle this situation but the code is on another machine and I forgot to check it in before I left. Now I will not be near that machine again for quite a while.  I can try to reproduce to code if needed.  I don't think it was much but I can't be sure I was not breaking something else.

**Comment by emersion** [comment]
I'd prefer not to allow clients to dictate what the new IDs will be. This is fragile and the spec doesn't require this behavior.

**Comment by D95-waka** [comment]
This behavior could save me lot of wrappers to create. Could it be done using some default to false flag on the daemons startup, or is it requiring too much changes and therefore would get the whole program to be more fragile?

**Comment by emersion** [comment]
mako supports the `x-canonical-private-synchronous`/`x-dunst-stack-tag` hints for simple use-cases.
