### ISSUE TITLE
is there any way to take a screenshot of a notification without being precise with the mouse?

### ISSUE THREAD

**Issue by treeshateorcs** [emersion/mako#481]
with dunst i could do

```
maim -su
```

and click at any point in a notification and maim would screenshoot the whole notification window, which doesn't seem to be the case with mako

this is my grim setup

```
WINDOWS=$(swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"')
echo "$WINDOWS" | slurp | grim -g - - | wl-copy && notify-send "screenshot captured"
```

**Comment by emersion** [comment]
No, there is no way to do this at the moment. This would require some Sway patches and I'm not sure we'd want these.
