### ISSUE TITLE
systemd user service ExecCondition checking for WAYLAND_DISPLAY fails, need to autostart in sway

### ISSUE THREAD

**Issue by krei-se** [emersion/mako#496]
I don't understand how a systemd-service in userspace for mako would ever work as there is no WAYLAND_DISPLAY set before sway is started.

Debugging the environment variables available in systemd userspace even after starting sway there is no DISPLAY or WAYLAND_DISPLAY available, thus the service will always fail.

Is there a better way to have mako running for all users?

**Comment by emersion** [comment]
One needs to use `systemctl import-environment ...` inside the Sway config.
