### ISSUE TITLE
Is there a way to only blur the background of the notification and not the margin/padding?

### ISSUE THREAD

**Issue by carschandler** [emersion/mako#501]
I'm using Hyprland as my compositor, which enables blurring certain windows or layers (the `notifications` layer is what targets mako's notifications). As you can see, the entire section is being blurred, when I'd like for only the background to be. I figure this because mako is actually opening a window occupying the entire space of the margin and padding but that part is just invisible. It would be awesome if there were a way to only blur the background! Thanks.

![image](https://github.com/emersion/mako/assets/92899389/867b8a7f-9126-4b63-bfab-3064e064f26d)

**Comment by emersion** [comment]
There is no standard Wayland protocol for blur at the moment. Even if there was, I don't think blur support is in scope for mako.

**Comment by emersion** [comment]
BTW, the fact that there is a blur effect at all is a unilateral decision of the compositor. mako is not involved here.

**Comment by carschandler** [comment]
Yeah I understand, I just thought that mako is probably defining what Hyprland interprets the area of the "layer" to be, which seems to be the snag here. I understand that blur itself is a very niche issue and isn't in scope for mako. Thanks for the replies!
