### ISSUE TITLE
Improve README's Running section

### ISSUE THREAD

**Issue by o0nd7ots** [emersion/mako#507]
As of right now Mako targets Sway on SystemD systems and offers support for other compositors and init systems.
This support as of right now is kind of neglected (see #505  and #88) .

I will try to improve it, each commit explaining why I did something and linking to this issue.

**Comment by emersion** [comment]
mako doesn't target systemd specifically. mako does assume that a D-Bus session bus is available, as required by the FreeDesktop notifications spec. systemd happens to setup a session bus by default, while in general for non-systemd distros there are extra steps to get that running. However, none of the session bus stuff is mako-specific.

**Comment by o0nd7ots** [comment]
This makes sense.

I'll fix the patch as soon as I can.

-------- Original Message --------

**Comment by o0nd7ots** [comment]
From what I can see this is fixed
