### ISSUE TITLE
Same ID on notification renders a new notification

### ISSUE THREAD

**Issue by apprehensions** [emersion/mako#510]
For example:
```
notify-send -r 27312 hello
notify-send -r 27312 hi
```
makes the following:
![image](https://github.com/emersion/mako/assets/47404953/f05a024b-d868-472c-9080-337bb40f000e)

Which is unexpected, since what is expected is for one notification, to remove duplicate entries.
This is inconvenient for scripts that increase the volume for example:
![20240323_192451](https://github.com/emersion/mako/assets/47404953/9cb82f7a-d6b1-4ed4-8011-b1302729a8bd)

**Comment by emersion** [comment]
This is by design. See discussion in https://github.com/emersion/mako/pull/168.

**Comment by apprehensions** [comment]
> There is a "tag" mechanism you can use instead for scripts.

Thanks! Sorry for spamming the pull requests and issue, you can instead link duplicates to #270, which for me suffices:
```
notify-send hi --hint=string:x-dunst-stack-tag:example
notify-send hello --hint=string:x-dunst-stack-tag:example
```
