### ISSUE TITLE
Invoke default action also for restored notifications

### ISSUE THREAD

**Issue by nando-digital** [emersion/mako#511]
When a restored notification (using makoctl) is being clicked on, it doesn't run the default action but rather dismisses it. I think it would be useful to have the same behavior for restored notification as for normal ones.

**Comment by emersion** [comment]
I think this is a limitation of the notification spec. Once a notification has been closed the app that opened it forgets about it.

**Comment by nando-digital** [comment]
Thank, I didn't know that. In that case there's nothing to be done except closing the issue
