### ISSUE TITLE
synchronous with notifi-send

### ISSUE THREAD

**Issue by gorylong** [emersion/mako#516]
I'm trying to make a progress bar for volume but can't figure it out, I'm wondering if you could consider supporting it.

test example:

```
while true
  do 
     vol=$((vol + 1)) 
     notify-send -t 4000 -h int:value:${vol} "VOLUMEN: ${vol}% " -h string:synchronous:volume
     sleep 1
  done
```

**Comment by emersion** [comment]
Mako supports `x-canonical-private-synchronous` and `x-dunst-stack-tag`, but not `synchronous`.
