### ISSUE TITLE
Mako cannot play sound if started automatically

### ISSUE THREAD

**Issue by mastermach50** [emersion/mako#519]
If mako is started automatically due to dbus activation, then it cannot use `exec mpv <filename>` to play a sound on notification.

> This can be solved on the user end by manually starting mako via the window manager or some other means

### System
```
WM: Hyprland (latest git version as of writing this)
OS: NixOS 23.11
```

**Comment by emersion** [comment]
Why can't MPV work in this situation?

**Comment by mastermach50** [comment]
> Why can't MPV work in this situation?

Not sure, the only difference between the processes is that the parent of mako is sh if started by Hyprland and systemd if started by dbus activation

**Comment by emersion** [comment]
Going to close this as mako can't do anything differently here. Problem is likely somewhere else in the stack.

**Comment by mastermach50** [comment]
It is some sort of "wayland cannot share stuff between processes" kid of thing

There are several weird behaviors if I start 2 sessions of Hyprland,
- In some cases the notification sound will be heard on the sessions that did not send the notification

**Comment by emersion** [comment]
I don't think it's related to Wayland at all. Note, by default there is only a single D-Bus session bus, one would need to create another one explicitly when starting a second session.

**Comment by mastermach50** [comment]
Then maybe pipewire?
