### ISSUE TITLE
What is 'app-name' in Wayland? how can i get the app-id?

### ISSUE THREAD

**Issue by winteriscariot** [emersion/mako#544]
I'm trying to figure out some custom actions on application notifications, and reading through the docs i notice the "app-name" option, but it's unclear to me what this refers to.

the docs use "Google Chrome" for the app name of Chrome, but since the app-id of that app in Wayland is `google-chrome`, it's unclear to me what I should put in as the app-name for any given app. it doesn't seem like app-name and app-id are the same thing.

did i miss something in the docs, or can this be clarified perhaps?

thanks!

**Comment by winteriscariot** [comment]
while i still would like to figure out how best to get the app-id, some testing has indicated that if i use whatever the title is on the desktop file of the app i'm looking for, that seems to do the trick.

**Comment by emersion** [comment]
It's an arbitrary string, which may not match app-id: https://specifications.freedesktop.org/notification-spec/latest/protocol.html
