### ISSUE TITLE
outer margin but only top

### ISSUE THREAD

**Issue by vdegenne** [emersion/mako#547]
I want to be able to add top margin to the whole list:

Reading the doc I tried `outer-margin=100` in the config and it kinda works but it's also spaced by 100 on the right..

I can't see anything in the doc showing how it needs to be done. Is it not a thing?

**Comment by emersion** [comment]
Related: https://github.com/emersion/mako/issues/527

**Comment by jtrees** [comment]
Did you check the `DIRECTIONAL VALUES` section in the manual? I think this should work for you:

```
outer-margin=100,0,0,0
```

**Comment by emersion** [comment]
Eh, forgot that we had this implemented already.

**Comment by vdegenne** [comment]
@jtrees Nice thanks!
