### ISSUE TITLE
Name conflict the the python template library, Mako

### ISSUE THREAD

**Issue by orbea** [emersion/mako#58]
I am not sure if you would consider this an issue, but I figure its worth pointing out that your project's name conflicts with the well known python template library, Mako.

http://www.makotemplates.org/
https://pypi.org/project/Mako/

This was momentarily confusing when I thought the other Mako made an updated release. :)

**Comment by emersion** [comment]
Ahah, yeah I don't really consider this as an issue. Thanks for asking though!
