### ISSUE TITLE
Changing fromat from configuration file does not recognize '\n' character

### ISSUE THREAD

**Issue by masozzi** [emersion/mako#61]
As an example: if you put`format=%s\n%b` in the config file, the notification result wold be   `Summary\nBody` (those are two value that i'm using for testing).
Debugging the line that mako gets from the config file, you get that the `\` char is escaped.
gdb output (breakpoint at config.c:378):
```
(gdb) p eq + 1
$1 = 0x555555572387 "%s\\n%b"
```

**Comment by emersion** [comment]
We should probably recognize `\n`. We probably want to only do this for `format`, and not for other options? This would require adding a function like `void unescape(char *str)`. Could you send a PR to do this?

**Comment by masozzi** [comment]
I thought about `bool parse_format(const char *string, char *out)` in `types.c`
and change `apply_style_option` to have `return spec->format = parse_format(value, style->format)`, sounds good?
Sure, i'll send a PR.

**Comment by emersion** [comment]
Sounds good!
