### ISSUE TITLE
Add option to group notifications with same title

### ISSUE THREAD

**Issue by cauebs** [emersion/mako#66]
I'm using Telegram Desktop and, when I receive several messages, the notifications pile up even if they are from the same person. There could be a way to group them and show the title (is it called summary?) only once, at the top.

**Comment by emersion** [comment]
Yeah. Dunst has a [setting to stack notifications which are exactly the same](https://github.com/dunst-project/dunst/commit/bf6c1a6406ad28899dec11504e3de87125e526d6), this feature would be a superset of that.

**Comment by vilhalmer** [comment]
I'm imagining configuring this using a list of criteria that must match, something like:
```
stack=app-name,summary,body  # dunst-like for most

[app-name=Telegram]
stack=summary  # group by conversation

[urgency=high]
stack=none
```
Don't know if we want to try to handle the OR case. Probably not. Maybe it should be something other than a comma to make it more obvious that it's AND.

Do we want to be fancy with this and allow them to be expanded somehow? Or are we ok with just erasing all but the top one and keeping track of a count, like dunst does?

**Comment by vilhalmer** [comment]
I'm starting to work on the design for this feature and I have a couple more questions:
- How should this interact with `sort-criteria`? Do we want stacking to always "win" and position the entire stack where the first notification in the stack would end up? Or do we sort first and then only stack ones that are adjacent to each other? (I am leaning toward the former, to increase the odds that stacking will happen.)
- Do we want to call this stacking, grouping, or some other third thing?

I think I've managed to fold both of the options in my previous question (keep all vs. only the top one) into the design using some new criteria, and it should also allow us to replace the current special-case implementation of `hidden` as well. I'm not going to share yet, until I know it works. :)

**Comment by cauebs** [comment]
Since this is going to be used almost exclusively by "power users", I think the best approach is to allow these things to be configurable.
About the naming, I think it's mostly bikeshedding, but I'd prefer "grouping".

**Comment by emersion** [comment]
>How should this interact with sort-criteria? Do we want stacking to always "win" and position the entire stack where the first notification in the stack would end up? Or do we sort first and then only stack ones that are adjacent to each other? (I am leaning toward the former, to increase the odds that stacking will happen.)

I agree with you: first grouping should happen, and then sorting.

>About the naming, I think it's mostly bikeshedding, but I'd prefer "grouping".

Same.

>and it should also allow us to replace the current special-case implementation of hidden as well.

Yay!

**Comment by 0xdec** [comment]
To add another related request to this feature: the ability to replace existing notifications would be great (similar to dunst's -r option). This would allow for e.g. volume display overlays that update their content whenever the volume is changed.

**Comment by 0xdec** [comment]
Oh wow, nice! I just tested it and it seems to work great. Thanks!
