### ISSUE TITLE
Right-clicking on the first notification dismisses all notifications

### ISSUE THREAD

**Issue by emersion** [emersion/mako#67]

**Comment by SirCmpwn** [comment]
Isn't it supposed to?

**Comment by emersion** [comment]
It should only dismiss one notification.

We should also make this configurable.

**Comment by SirCmpwn** [comment]
I thought it was left click to dismiss one, right click to dismiss all.

**Comment by emersion** [comment]
Left click activates one (e.g. focuses Firefox if the notification comes from Firefox), right click dismisses one (just removes it without activating it).

**Comment by michaelnew** [comment]
Since right-click dismisses a single notification now, is there any way to dismiss all of them? Sometimes I'm stuck right-clicking through piles of notifications if I haven't used my computer in a while.

**Comment by vilhalmer** [comment]
`makoctl dismiss --all`
