### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [emersion/mako#73]
The function “[calloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/calloc.html "Memory allocation")” does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function “[handle_signal](https://github.com/emersion/mako/blob/3d928d1f8e0b6fbfd4a445835078e05153266844/main.c#L65 "Update candidate")”.

**Comment by emersion** [comment]
Indeed. Maybe we can have a special file descriptor that we close instead to request the event loop to stop?

**Comment by elfring** [comment]
Would you like to consider other software design options?
- [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html)
- [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html)
- [Signal-safe locks](https://locklessinc.com/articles/signalsafe_locks/)

**Comment by vilhalmer** [comment]
Self-pipe seems like it would be the easiest to fit into the event loop.

**Comment by emersion** [comment]
Fixed in https://github.com/emersion/mako/pull/79
