### ISSUE TITLE
sd_bus_request_name requires dbus policy

### ISSUE THREAD

**Issue by DanySpin97** [emersion/mako#80]
Running mako I get this error:
`Failed to acquire service name: Permission denied`

Following [this thread](https://stackoverflow.com/questions/32828468/sd-bus-api-sd-bus-request-name-returns-permission-denied) now mako works.

Related [issue](https://github.com/elogind/elogind/issues/87).

**Comment by emersion** [comment]
This happens because the system bus is used instead of the user bus, even when `sd_bus_open_user` is used.

https://github.com/elogind/elogind/blob/c552a8e6e51f69d5afc5deb724fd9ae184a4fbe7/src/libelogind/sd-bus/sd-bus.c#L1366
