### ISSUE TITLE
Bottom margin not added to bottom item when bottom-anchored

### ISSUE THREAD

**Issue by jeremejevs** [emersion/mako#82]
In other words, `bottom-left` and `bottom-right` results in the notifications being glued to the top of the swaybar, regardless of the bottom margin. This isn't the case for the top. Happens in the current version, but not in 1.1. Probably #74?

**Comment by vilhalmer** [comment]
Ah yeah, good catch. I removed the margin around the surface which means we have to do it ourselves for the last notification we render.
