### ISSUE TITLE
Center position for notifications

### ISSUE THREAD

**Issue by hpdeifel** [emersion/mako#86]
It would be nice to have the ability to center notifications on the screen (horizontally, don't know if anyone would want to center them vertically) without manually calculating margins.

**Comment by emersion** [comment]
It would be pretty easy to do: add `anchor` values, change `config->anchor` to be only one edge:

https://github.com/emersion/mako/blob/e6aaa2495f01612098b5519ea4b4e6cecc81e957/config.c#L306

Would you be willing to send a PR?
