### ISSUE TITLE
History and history redisplay

### ISSUE THREAD

**Issue by Emantor** [emersion/mako#91]
Feature request:
Keep a history of configurable length which can be redisplayed using makoctl (similar to dunsts history handling)

**Comment by vilhalmer** [comment]
I am a fan of having them accessible via makoctl, though I'd probably lean toward having both methods available and having a `makoctl redisplay N` or similar for the dunst behavior instead of a built-in keybinding. Max history length of -1 could mean "infinite" as well.

**Comment by Difrex** [comment]
Any progress on it? It's a really important feature that I need.

**Comment by emersion** [comment]
Feel free to send patches.

**Comment by MichaelAquilina** [comment]
So I've started giving the source code a look to see if I could add this in myself. Hooking into `dbus/mako.c` looks simple enough. However it seems like we currently do not track history of notifications in any way - so that would have to change. Is there any way you would suggest looking into this?

**Comment by vilhalmer** [comment]
I haven't put a whole lot of thought into this, but the simplest implementation would probably be another linked list on the mako struct where we put notifications instead of destroying them. I don't think you need to worry about ever updating their styles, since they're a "thing of the past" so to speak. Then when you want to redisplay them, you could simply grab them in reverse order and put them back into the normal list.

One of the concerns I do have is using a large chunk of memory when icons/images are present, but I don't think we need to tackle that for the first attempt. Better to see what problems really arise after using it for a while.

**Comment by matt-snider** [comment]
@MichaelAquilina @vilhalmer Consider having a look at the implementation used in [dunst](https://github.com/dunst-project/dunst).

From a quick look over the code these seem to be some of the important bits:

* Notification is created [here](https://github.com/dunst-project/dunst/blob/59a87e4e998d89c6571ff0558aa261d247c7636c/src/dbus.c#L315)
    * Calls [queues_notification_insert()](https://github.com/dunst-project/dunst/blob/6c4eeda43412f0ecd0e38e00069ca47aff4452a8/src/queues.c#L160) which adds it to the pending notification list
* Notification is dismissed [here](https://github.com/dunst-project/dunst/blob/ac94eca79e37a50c7b531f2706de631c24f86276/src/x11/x.c#L307) when key bound to dismiss is pressed
    * Calls [queues_notification_close()](https://github.com/dunst-project/dunst/blob/6c4eeda43412f0ecd0e38e00069ca47aff4452a8/src/queues.c#L334)
    * Calls [queues_history_push()](https://github.com/dunst-project/dunst/blob/6c4eeda43412f0ecd0e38e00069ca47aff4452a8/src/queues.c#L353)

**Comment by kuon** [comment]
I am sorry I do not have time to work on this, but here is a suggestion on how to implement it:

### Config file

- `history=0|1` enable history feature
- `max-history=100` the amount of notification to remember

### Makoctl

- `history` query history for machine parsing, it should have a `clear` sub-command to be emptied
- `redisplay` requeue history notification in reverse order (most recent to oldest).  It should not honor `group_by` and just push notifications one by one. 

Both commands should support `-n` to limit the number of returned item, `-f` to filter the items (using CRITERIA).

**Comment by jktr** [comment]
I've tried to implement the history feature based on this discussion in #220. The implementation is basically the one described by @vilhalmer and the config settings are as described by @kuon.

It doesn't support all the requested feature yet, but should provide a starting point for further enhancements. I'd appreciate any feedback.

**Comment by RobinOpletal** [comment]
@emersion Would it be possible for you to document the usage of this in a manpage?

**Comment by emersion** [comment]
Already documented:

* https://github.com/emersion/mako/blob/master/makoctl.1.scd#L28
* https://github.com/emersion/mako/blob/master/mako.5.scd#L25

**Comment by RobinOpletal** [comment]
Thank you

**Comment by robert-zaremba** [comment]
`mako history` is still not released.

**Comment by trinitronx** [comment]
@robert-zaremba:

> `mako history` is still not released.

Try: `makoctl history`

Also check docs mentioned above:

- [`man makoctl`][1]: `history` & `restore` commands
- [`man 5 mako`][2]: `max-history=n` & `history=0|1` config options


Some useful one-liners that use this:

- Open last screenshot in [`dragon-drop`][3]

      makoctl history | jq -r '.data | .[] | map(select(.summary.data == "Screenshot saved")) | first | .body.data'  | xargs dragon-drop -s 400 --stdin

- Open last screenshot in [`imv`][4]

      makoctl history | jq -r '.data | .[] | map(select(.summary.data == "Screenshot saved")) | first | .body.data'  | xargs imv

- Open last screen recording in [`mpv`][5]

      makoctl history | jq -r '.data | .[] | map(select(.summary.data == "Recording" and (.body.data | match("Finished recording")))) | .[0:4] | .[].body.data' | sed -e 's/Finished recording \?//g'  | xargs  mpv --hwdec=vaapi --vo=dmabuf-wayland 


[1]: https://github.com/emersion/mako/blob/master/makoctl.1.scd#commands
[2]: https://github.com/emersion/mako/blob/master/mako.5.scd#global-configuration-options
[3]: https://aur.archlinux.org/packages/dragon-drop
[4]: https://sr.ht/~exec64/imv/
[5]: https://mpv.io/
