### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by CameronNemo** [emersion/mako#96]
Hello,

I would like to respectfully ask that you tag a release in the near future. Support for libelogind was recently added, and the supported version of elogind was recently released. I would like to package mako in void linux, and a tagged release is necessary.

Thank you for your awesome project!

**Comment by vilhalmer** [comment]
We could probably call the current state 1.2, the open issues are primarily enhancements and things have been pretty stable. The only thing we might want to take care of first is #72.

**Comment by emersion** [comment]
https://github.com/emersion/mako/releases/tag/v1.2
